#pragma config(Motor,  port6,           armAngle,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftArm,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           servoGrab,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		motor[leftArm] = vexRT[Ch2]/2;
		motor[rightArm] = vexRT[Ch2]/2;
		motor[armAngle] = vexRT[Ch1]/2;
		if(vexRT[Btn5U] == 1) {
			motor[servoGrab] = 127;
		}
		else if (vexRT[Btn5U] == 0) {
			motor[servoGrab] = 0;
		}
	}
} //this is some dank code
