#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		motor[leftArm] = vexRT[Ch2]; //get input from the right side controller joystick and assign it to the left side arm
		motor[rightArm] = vexRT[Ch2];
		if(vexRT[Btn5U] == 1) { //if the left shoulder button is enabled
			motor[clawMotor] = -63;
		}
		else if (vexRT[Btn5D] == 1){
			motor[clawMotor] = 63;
		}
	}
