#pragma config(Sensor, dgtl1,  Sol1,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  Sol2,           sensorDigitalOut)
#pragma config(Sensor, dgtl3,  Encode1,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Poten,          sensorRotation)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Base1,         tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Base2,         tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           Claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LIft2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Lift3,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(300)
#pragma userControlDuration(900)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	motor[port3] = 0;
	motor[port4] = 0;
	SensorValue(Sol1) = 1;
	SensorValue(Sol2) = 1;// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	while(true)
	{
		SensorValue(dgtl1) = 0;// lower solenoid
		SensorValue(dgtl2) = 0;
		SensorValue(dgtl3) = 0;
		waitInMilliseconds(500);
		motor[port5] = -80;
		motor[port6] = -127; // raise lift
		motor[port7] = -127;
		motor[port8] = -127;
		wait(1);
		motor[port6] = 0; // stop lift
		motor[port7] = 0;
		waitInMilliseconds(500);
		motor[port3] = 127;
		motor[port4] = 127;
		waitInMilliseconds(800);
		motor[port3] = 127;
		motor[port4] = 127;
		waitInMilliseconds(500);
		motor[port3] = 0; // stop moving
		motor[port4] = 0;
		motor[port5] = 50; // release cone
		waitInMilliseconds(500);
		motor[port5] = 0; // stop intake
		motor[port3] = -127; // move backward
		motor[port4] = -127;
		wait(1);
		motor[port3] = 0;
		motor[port4] = 0;
		wait(10);


		//if(SensorValue[dgtl1] == 0) //dist
	//	{
		//	motor[port3] = 127; // turn 90 degrees right
			//motor[port4] = -127;
		//}
		//SensorValue[dgtl3] = 0;
		///if(SensorValue[dgtl1] == 50) //dist
		//{
			//motor[port4] = 127; // move forward
		//}
		//SensorValue[dgtl3] = 0;
		//if(SensorValue[dgtl1] == 2750) //dist
		//{
			//motor[port3] = 0; // stop moving
			//motor[port4] = 0;
		//}
	//	SensorValue[dgtl3] = 0;
	//	wait(1);
		//SensorValue[dgtl1] = 1; // lift mobile goal
	//	SensorValue[dgtl2] = 1;
	//wait(1);
	//	motor[port3] = -127; // turn 180 degrees to left
		//motor[port4] = 127;
		//if(SensorValue[dgtl1] == 50) //dist
		//{
			//motor[port3] = 0; // stop moving
			//motor[port4] = 0;
		//}
		//SensorValue[dgtl3] = 0;
	//	wait(1);
	//	SensorValue(dgtl1) = 0; // lower mobile goal
		//SensorValue(dgtl2) = 0;
		//wait(1);
	//	motor[port3] = -127; // move backward
	//	motor[port4] = -127;
		//if(SensorValue[dgtl1] == 1000) //dist
		//{
			//motor[port3] = 0; // stop moving, autonomous complete
			//motor[port4] =0;
		//}
		//SensorValue[dgtl3] = 0;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()

// User control code here, inside the loop //


{
	while(1==1)
	{
		motor[port3] = vexRT[Ch2]; // drive
		motor[port4] = vexRT[Ch3];
		if(vexRT[Btn8D] == 1)       	// If button 6U is pressed:
		{
			SensorValue[Sol2] = 1;			// activate the solenoid.
			SensorValue[Sol1] = 1;
		}
		if(vexRT[Btn8L] == 1)							// If button 5U is pressed
		{
			SensorValue[Sol2] = 0;			// ...deactivate the solenoid.
			SensorValue[Sol1] = 0;
		}
		if(vexRT[Btn5U] == 1) // intake down
		{
			motor[port5] = 50;
		}
		else if(vexRT[Btn6U] ==1) // intake up
		{
			motor[port5] = -50;
		}
		else if(vexRT[Btn8R] ==1)
		{
			motor[port5] = 0;
		}
		if(vexRT[Btn5D] ==1) //lift down
		{
			motor[port6] = 127;
			motor[port7] = 127;
			motor[port8] = 127;
		}
		else if(vexRT[Btn6D] ==1) // lift up
		{
			motor[port6] = -127;
			motor[port7] = -127;
			motor[port8] = -127;
		}
		else
		{
			motor[port6] = 0;
			motor[port7] = 0;
			motor[port8] = 0;
		}
	}



}
