#pragma config(Motor,  port6,           rightAngle,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftArm,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           servoGrab,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
motor[leftArm] = vexRT[Ch1];
motor[rightArm] = vexRT[Ch1];
motor[servoGrab] = vexRT[Ch2];
motor[rightAngle] = vexRT[Ch2];

}
} //this is some dank code
