//Copyright, Arjun Vedantham 2017

#pragma config(Sensor, dgtl5,  BumpSwitch,     sensorTouch)
#pragma config(Motor,  port2,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) { //keep listening forever so that we can run this without USB
	untilBump(BumpSwitch); //listen for bump switch trigger
	startMotor(BackLeft, 63); //start all the motors
	startMotor(BackRight, -63);
	startMotor(FrontLeft, 63);
	startMotor(FrontRight, -63);
	untilBump(BumpSwitch); //until there is another button press
	stopMotor(BackLeft); //stop all the motors
	stopMotor(BackRight);
	stopMotor(FrontLeft);
	stopMotor(FrontRight);
}
}
