#pragma config(Motor,  port2,           yourMotorHere, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
if(vexRT[Btn6U] == 1) {
	motor[yourMotorHere] = 127;
}
else if(vexRT[Btn6D] == 1) {
	motor[yourMotorHere] = -127;
}
else if (vexRT[Btn6D] == 0 && vexRT[Btn6U] == 0) {
	motor[yourMotorHere] = 0;
}


}
