#pragma config(Sensor, in1,    greeksensor,    sensorGyro)
#pragma config(Sensor, in7,    clawwidth,      sensorPotentiometer)
#pragma config(Sensor, in8,    Leverangle,     sensorPotentiometer)
#pragma config(Sensor, dgtl5,  Green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  Yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  Red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  Encoderright,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Encoderleft,    sensorQuadEncoder)
#pragma config(Motor,  port2,           Rightside,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Leftside,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Leftarm2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Leftarm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rightarm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Rightarm2,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(300)
#pragma userControlDuration(900)
#include "Vex_Competition_Includes.c"   //Main competit
//ion background code...do not modify!


int 	dumbpotentiometerthignalisonwants;
void pre_auton()
{
	dumbpotentiometerthignalisonwants = SensorValue(Leverangle);
}

int dunderedoneclawpotendontdunworkin;

//====================================================//
//																										//
//					HEY LOOK! IT'S AUTONOMOUS!                //
//																										//
//																										//
//====================================================//


void autonomousexe() ////Autonomous is in a void to ease calling it to action
{SensorValue(dgtl9)=0;
SensorValue(dgtl11)=0;

	if(SensorValue[Leverangle]>2750){
	{while(SensorValue[Leverangle]>2750){
		motor[Leftarm] = -127;
		motor[port6] = -127; //bottom left
		motor[Rightarm] = 127;
		motor[port9]= 127; //bottom right
	}}
	motor[Leftarm] = -0;
		motor[port6] = -0; //bottom left
		motor[Rightarm] = 0;
		motor[port9]= 0; //bottom right

	while(SensorValue[clawwidth]>2400)
	{
		motor[claw2]=-100;
		motor[claw]=-100;
	}

		motor[claw2]=0;
		motor[claw]=-0;
		motor(Rightside) =127;
		motor(Leftside)=127;

		wait(1.5);
		motor[claw2]=0;
		motor[claw]=-0;
		motor(Rightside) =-127;
		motor(Leftside)=-127;

		wait(0.6);

					motor[Leftside]=0;
				motor[Rightside]=0;
				wait(0.1);


			wait(0.1);/////////Donewiththebackingupness/////////////////////////////////////////////
			motor(Rightside)=127;
			motor(Leftside)=-127;
			wait(0.6);
			motor(Rightside)=0;
			motor(Leftside)=0;

			motor[Leftarm] = 127;
			motor[port6] = 127; //bottom left
			motor[Rightarm] = -127;
			motor[port9]= -127;

			motor(claw)=95;
			motor(claw2)=95;

			wait(0.9);
				motor[Leftarm] = 0;
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -0;
			motor[port9]= -0;
			motor(claw)=0;
			motor(claw2)=0;
			wait(1);

		///////////GOOOOOOOOOO
			motor(claw)=-127;
			motor(claw2)=-127;
			wait(1.8);
			motor(claw)=0;
			motor(Claw2)=0;
			wait(0.5);
			motor(claw)=-50;
			motor(claw2)=-50;
			motor(Leftside)=-127;
			motor(Rightside)=-127;
			wait(0.6);
			motor[Leftarm] = -100; /////stop the arm
			motor[port6] = -100; //bottom left
			motor[Rightarm] = 100;
			motor[port9]= 100;
			wait(1.7);
			motor(claw)=127;
			motor(claw2)=127;
			motor[Leftarm] = 00; /////stop the arm
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -00;
			motor[port9]= 00;
			motor(Leftside)=0;
			motor(Rightside)=0;
			wait(0.7);
			motor(claw)=0;
			motor(claw2)=0;
			motor[Leftarm] = 100; /////stop the armde
			motor[port6] = 100; //bottom left
			motor[Rightarm] = -100;
			motor[port9]= -100;
			motor(Leftside)=100;
			motor(Rightside)=100;
			wait(1.3);
				motor(Leftside)=0;
			motor(Rightside)=0;
	motor[Leftarm] = 0; /////stop the armde
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -0;
			motor[port9]= -0;

		//////////REPEAT 2
					motor(claw)=-127;
			motor(claw2)=-127;
			wait(1.8);
			motor(claw)=0;
			motor(Claw2)=0;
			wait(0.5);
			motor(claw)=-50;
			motor(claw2)=-50;
			motor(Leftside)=-127;
			motor(Rightside)=-127;
			wait(0.6);
			motor[Leftarm] = -100; /////stop the arm
			motor[port6] = -100; //bottom left
			motor[Rightarm] = 100;
			motor[port9]= 100;
			wait(1.7);
			motor(claw)=127;
			motor(claw2)=127;
			motor[Leftarm] = 00; /////stop the arm
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -00;
			motor[port9]= 00;
			motor(Leftside)=0;
			motor(Rightside)=0;
			wait(0.7);
			motor(claw)=0;
			motor(claw2)=0;
			motor[Leftarm] = 100; /////stop the armde
			motor[port6] = 100; //bottom left
			motor[Rightarm] = -100;
			motor[port9]= -100;
			motor(Leftside)=100;
			motor(Rightside)=100;
			wait(1.3);
				motor(Leftside)=0;
			motor(Rightside)=0;
	motor[Leftarm] = 0; /////stop the armde
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -0;
			motor[port9]= -0;
//////REPEAT 3
					motor(claw)=-127;
			motor(claw2)=-127;
			wait(1.8);
			motor(claw)=0;
			motor(Claw2)=0;
			wait(0.5);
			motor(claw)=-50;
			motor(claw2)=-50;
			motor(Leftside)=-127;
			motor(Rightside)=-127;
			wait(0.7);
			motor[Leftarm] = -100; /////stop the arm
			motor[port6] = -100; //bottom left
			motor[Rightarm] = 100;
			motor[port9]= 100;
			wait(1.7);
			motor(claw)=127;
			motor(claw2)=127;
			motor[Leftarm] = 00; /////stop the arm
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -00;
			motor[port9]= 00;
			motor(Leftside)=0;
			motor(Rightside)=0;
			wait(0.7);
			motor(claw)=0;
			motor(claw2)=0;
			motor[Leftarm] = 110; /////stop the armde
			motor[port6] = 110; //bottom left
			motor[Rightarm] = -110;
			motor[port9]= -110;
			motor(Leftside)=100;
			motor(Rightside)=100;
			wait(1.3);
				motor(Leftside)=0;
			motor(Rightside)=0;
	motor[Leftarm] = 0; /////stop the armde
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -0;
			motor[port9]= -0;
///REPEAT4
					motor(claw)=-127;
			motor(claw2)=-127;
			wait(1.8);
			motor(claw)=0;
			motor(Claw2)=0;
			wait(0.5);
			motor(claw)=-50;
			motor(claw2)=-50;
			motor(Leftside)=-127;
			motor(Rightside)=-127;
			wait(0.6);
			motor[Leftarm] = -100; /////stop the arm
			motor[port6] = -100; //bottom left
			motor[Rightarm] = 100;
			motor[port9]= 100;
			wait(1.7);
			motor(claw)=127;
			motor(claw2)=127;
			motor[Leftarm] = 00; /////stop the arm
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -00;
			motor[port9]= 00;
			motor(Leftside)=0;
			motor(Rightside)=0;
			wait(0.7);
			motor(claw)=0;
			motor(claw2)=0;
			motor[Leftarm] = 100; /////stop the armde
			motor[port6] = 100; //bottom left
			motor[Rightarm] = -100;
			motor[port9]= -100;
			motor(Leftside)=100;
			motor(Rightside)=100;
			wait(1.3);
				motor(Leftside)=0;
			motor(Rightside)=0;
	motor[Leftarm] = 0; /////stop the armde
			motor[port6] = 0; //bottom left
			motor[Rightarm] = -0;
			motor[port9]= -0;



			motor(Leftside)=50;
			motor(Rightside)=50;
			wait(0.4);
			motor(Leftside)=0;
			motor(Rightside)=0;
		motor[Leftarm] = -127;
		motor[port6] = -127; //bottom left
		motor[Rightarm] = 127;
		motor[port9]= 127;
		motor(claw)=60;
		motor(claw2)= 60;
		///negative is close
		wait(0.8);
				motor[Leftarm] = -0;
		motor[port6] = -0; //bottom left
		motor[Rightarm] = 0;
		motor[port9]= 0;
		motor(claw)=0;
		motor(claw2)= 0;

			///////normalcodestart////////////////
/*
	motor(claw) = -60; ////Close CLAW SPEED
	motor(claw2) = -60;

	wait(0.4);

	motor(Leftside) = -127;
	motor(Rightside) = 127;

	wait(0.8);
	motor(Leftside) = 0;
	motor(Rightside) = 0;
	wait(0.4);


	motor(claw) = 0;
	motor(claw2) = 0;

	motor(Leftside) = 127;//////////STARS PICKUP/////LENGH: .7 SECONDS/////
	motor(Rightside) = 127;

	motor[Leftarm] = -0; //////This lifts arm so arm does not immediantly hit floor////
	motor[port6] = -0; //bottom left
	motor[Rightarm] = 0;
	motor[port9]= 0; //bo

	//bottom right

	wait(0.3);///////Stop opening the claw after ____ seconds////



	wait(0.4);

	motor(Leftside) = 127;
	motor(Rightside) = 127; //////////////////////PICKUP PART 2 (Closeing the claw)

	motor(claw) = -85; ///negative is close
	motor(claw2) = -85;

	wait(0.4);

	motor(Leftside) = -127;
	motor(Rightside) = -127;

	wait(0.6);

	motor(Leftside) = -127;
	motor(Rightside) = 0;

	motor(claw) = -30; /////This holds the claw tighter in while turning
	motor(claw2) = -30; ////so stars dont slip

	motor[Leftarm] = -30;
	motor[port6] = -30; //bottom left
	motor[Rightarm] = 30;
	motor[port9]= 30; //bottom right

	wait(1.05);

	motor(Leftside) = -127; ///// This makes us simply move closer to the fence
	motor(Rightside) = -127;

	motor[Leftarm] = -40;
	motor[port6] = -40; //bottom left
	motor[Rightarm] = 40;
	motor[port9]= 40; //bottom right

	wait(1);


	motor(Leftside) = -50;
	motor(Rightside) = 0;


	while(SensorValue(in8)>1300)
	{
		motor[Leftarm] = -100; /////////SCORE THE STARS//LENGTH: 1.4 Secs///////////
		motor[port6] = -100;
		motor[Rightarm] = 100; ////speed at which the arm dumps stars
		motor[port9]= 100;
	}

	motor[Leftarm] = -0; ////Slowly lower arm more in case of errors
	motor[port6] = -0; //bottom left
	motor[Rightarm] = 0;
	motor[port9]= 0; //bottom right




	motor(claw) = 127; ////open the claw
	motor(claw2) = 127; ///negative is close

	wait (0.5);

	motor(claw) = 20;
	motor(claw2) = 20;

	wait (0.3);

	motor(Rightside) = 0;
	motor(Leftside) = 0;
	///Stop everything
	motor(claw) = 0;
	motor(claw2) = 0;
	///Fin
	wait(0.4);
	motor[Leftarm] = 100; /////stop the arm
	motor[port6] = 100; //bottom left
	motor[Rightarm] = -100;
	motor[port9]= -100; //bottom right
	wait(1);
	motor[Leftarm] = -0; /////stop the arm
	motor[port6] = -0; //bottom left
	motor[Rightarm] = 0;
	motor[port9]= 0;

*/

}

}





task autonomous()
{

	autonomousexe();

}

task usercontrol()
{
	while(1==1)
	{
			if (vexRT[Btn7U]==1 )
	{
		motor[Leftarm] = -127;
		motor[port6] = -127; //bottom left
		motor[Rightarm] = 127;
		motor[port9]= 127; //bottom right
	}

		 else if (vexRT[Btn7D]==1 )
	{
		motor[Leftarm] = 60;
		motor[port6] = 60; //bottom left
		motor[Rightarm] = -60;
		motor[port9]= -60; //bottom right
	}

		else
	{
			motor[Leftarm] = 0;
		motor[port6] = 0; //bottom left
		motor[Rightarm] = -0;
		motor[port9]= 0; //bottom
}

	if(vexRT[Btn7L]==1)
	{
		motor[claw]=60;
		motor[claw2]=60;

	}

	else if(vexRT[Btn7R]==1)
	{
		motor[claw]=-60;
		motor[claw2]=-60;
	}


	else
	{
		motor[claw]=0;
		motor[claw2]=0;
	}

	if(vexRT[Btn8U]==1)
	{
		motor(Leftside)=100;
		motor(Rightside)=100;
	}

	else if(vexRT[Btn8D]==1)
	{
		motor(Leftside)=-100;
		motor(Rightside)=-100;
	}
	else if(VexRT[Btn8R]==1)
	{
		motor(Leftside)=-75;
		motor(Rightside)=75;
	}
	else if(vexRT[Btn8L]==1)
	{
		motor(Leftside)=75;
		motor(Rightside)=-75;
	}

	else
	{
		motor(Leftside)=0;
		motor(Rightside)=0;
	}



	}
}
