#pragma config(Motor,  port7,           Leftarm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rightarm,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if (vexRT[Btn5U]==1)
		{
			motor[Leftarm] = -127;
			motor[Rightarm] = 127;
		}
		else if (vexRT[Btn5D]==1)
		{
			motor[Leftarm] = 127;
			motor[Rightarm] = -127;
		}

		else
		{
			motor[Leftarm] = 0;
			motor[Rightarm] = 0;
		}
	}

}
