#pragma config(Sensor, dgtl1,  leftswitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  rightswitch,    sensorTouch)
#pragma config(Motor,  port2,           Rightside,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           MiddleMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Leftside,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(300)
#pragma userControlDuration(900)
#include "Vex_Competition_Includes.c"   //Main competit
//ion background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{ ////epic code//////////////
	////4ft in 2.5 sec//





	////fin

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task movement()
{

	motor[Rightside] = vexRT[Ch2];
	motor[Leftside] = vexRT[Ch3];

	if(vexRT[Btn6D]==1)
	{
		motor[MiddleMotor]=127;
	}

	else if(vexRT[Btn5D]==1)
	{
		motor[MiddleMotor]=-127;
	}

	else
	{
		stopMotor(MiddleMotor);
	}
}
task shooting()
{

	if(vexRT[Btn7U]==1)
	{
		motor[arm] = 127;
	}

	else if(vexRT[Btn7D]==1)
	{
		motor[arm] = -127;
	}

	else if(vexRT[Btn8U]==1)
	{
		motor[claw] = -127;
	}
	else if (vexRT[Btn8D]==1)
	{
		motor[claw] = -127;
	}
}
task usercontrol()
{
	// User control code here, inside the loop //
	while(1==1)
	{

		startTask (movement);
		startTask (shooting);
		//startTask (switchtest);
	}
}
