#pragma config(Sensor, in8,    Leverangle,     sensorPotentiometer)
#pragma config(Sensor, dgtl5,  Green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  Yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  Red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, Encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           Rightside,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Leftside,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Leftarm2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Leftarm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rightarm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Rightarm2,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(300)
#pragma userControlDuration(900)
#include "Vex_Competition_Includes.c"   //Main competit
//ion background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

////////////////////////////////////////////////////////////////////////
// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
/////////////////////////////////////////////////////////////////////////




}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



//int autonomousside = 0     ;
/////0 = Go forward, go LEFT
/////1 = Go forward, go RIGHT



//====================================================//
//																										//
//					HEY LOOK! IT'S AUTONOMOUS!                //
//																										//
//																										//
//====================================================//

int gotoautonomous = 7;

int chooseautonomous =1;
//// 1 = LEFT SIDE ( TURN RIGHT)
//// 2 = RIGHT SIDE (TURN LEFT)
//// 0 = DO NOTHING
////SIDES ARE POINTED TOWARDS FENCE
///////GREEN LED = Leftside on
///////RED LED = Rightside on

void autonomousexe() ////Autonomous is in a void to ease calling it to action
{



while(SensorValue(in8)>3950 && SensorValue(in8) <4000 )
{///////////ENCODERSTUFF
	//////////HIGHER NUMBER IS LOWER
///////////// LOWER NUMBER IS HIGHER


	if(SensorValue(in8)>3920)///////If the arm is LOWER than
	{
		motor[Leftarm] = -20;
		motor[port6] = -20; //bottom left
		motor[Rightarm] = 20;
		motor[port9]= 20; //bottom right
}

if(SensorValue(in8)<4000)///////if arm is HIGHER than
{
  	motor[Leftarm] = 20;
		motor[port6] = 20; //bottom left
		motor[Rightarm] = -20;
		motor[port9]= -20;

}
}
wait(0.2);

motor(claw) = -60; ////OPEN CLAW SPEED
motor(claw2) = -60;

motor[Leftarm] = -2; //////This lifts arm so arm does not immediantly hit floor////
motor[port6] = -0; //bottom left
motor[Rightarm] = 2;
motor[port9]= 0;

wait(0.15);


motor(Leftside) = 127;//////////STARS PICKUP/////LENGH: .7 SECONDS/////
motor(Rightside) = 127;

motor(claw) = 60; ////OPEN CLAW SPEED
motor(claw2) = 60;

motor[Leftarm] = -0; //////This lifts arm so arm does not immediantly hit floor////
motor[port6] = -0; //bottom left
motor[Rightarm] = 0;
motor[port9]= 0; //bo

 //bottom right

wait(0.3);///////Stop opening the claw after ____ seconds////

motor(claw) = 0;
motor(claw2) = 0;

wait(0.5);

motor(Leftside) = 127;
motor(Rightside) = 127; //////////////////////PICKUP PART 2 (Closeing the claw)
wait(.25)

motor(claw) = -40; ///negative is close(
motor(claw2) = -40;

wait(0.5);

motor(Leftside) = -127;
motor(Rightside) = -127;

wait(0);

if(chooseautonomous == 1) ////This decides the direction.
	//DO NOT MODIFY THIS DIRECTLY!//
{
motor(Leftside) = 0;
motor(Rightside) = -127; /////TURNING BACKUP///////
}
else
{
	motor(Leftside) = -127;
	motor(Rightside) = 0;
}

motor(claw) = -30; /////This holds the claw tighter in while turning
motor(claw2) = -30; ////so stars dont slip

	motor[Leftarm] = -30;
		motor[port6] = -30; //bottom left
		motor[Rightarm] = 30;
		motor[port9]= 30; //bottom right

		wait(1.3);

		motor(Leftside) = -127; ///// This makes us simply move closer to the fence
		motor(Rightside) = -127;

			motor[Leftarm] = -40;
		motor[port6] = -40; //bottom left
		motor[Rightarm] = 40;
		motor[port9]= 40; //bottom right

		wait(1);

		if(chooseautonomous == 1) ////This section allows us to compensate if the turn is too sharp; realigns robot
		{
		motor(Leftside) = 0;
		motor(Rightside) = -50;
	}
	else
	{
		motor(Leftside) = -50;
		motor(Rightside) = 0;
	}


		motor[Leftarm] = -100; /////////SCORE THE STARS//LENGTH: 1.4 Secs///////////
		motor[port6] = -100;
		motor[Rightarm] = 100; ////speed at which the arm dumps stars
		motor[port9]= 100;

		wait(1);

				motor[Leftarm] = -0; ////Slowly lower arm more in case of errors
		motor[port6] = -0; //bottom left
		motor[Rightarm] = 0;
		motor[port9]= 0; //bottom right




		motor(claw) = 127; ////open the claw
		motor(claw2) = 127; ///negative is close

		wait (0.5);

			motor(claw) = 20;
		motor(claw2) = 20;

				motor[Leftarm] = -0; /////stop the arm
		motor[port6] = -0; //bottom left
		motor[Rightarm] = 0;
		motor[port9]= 0; //bottom right

		wait (0.6);

		motor(Rightside) = 0;
		motor(Leftside) = 0;
///Stop everything
		motor(claw) = 0;
		motor(claw2) = 0;
		///Fin

}





task autonomous()
{

if(chooseautonomous==0)
{
	motor(claw) = -30;
motor(claw2) = -30;  ///////SETUP SECTION///LENGTH: .15 SECODNS////

motor[Leftarm] = -90; //////This lifts arm so arm does not immediantly hit floor////
motor[port6] = -90; //bottom left
motor[Rightarm] = 90;
motor[port9]= 90; //bottom right

motor(Leftside) = -50; //////This moves us back slightly so arm doesnt hit stars
motor(Rightside) = -50;
wait(0.3);
motor(claw) = 0;
motor(claw2) = 0;

wait(0.4);
motor[Leftarm] = -0; //////This lifts arm so arm does not immediantly hit floor////
motor[port6] = -0; //bottom left
motor[Rightarm] = 0;
motor[port9]= 0; //bottom right

motor(Leftside) = -0; //////This moves us back slightly so arm doesnt hit stars
motor(Rightside) = -0;

}
else
{
autonomousexe();
}

	/*
Just call the void for autonomous
Its easier to call it if it isnt
in two places at once

	*/
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////




task movement()
{

	motor[Rightside] = vexRT[Ch2]; /////The wheels directly spin
	motor[Leftside] = vexRT[Ch3];//////With the imput of the joysticks

	if(vexRT[Btn8L]==1)
	{
		motor[Rightside] = 25;
		motor[Leftside] = -25;
	}

	if(vexRT[Btn8R]==1)
	{
		motor[Rightside] = -25;
		motor[Leftside] = 25;
	}

	else
	{
	motor[Rightside] = vexRT[Ch2]; /////The wheels directly spin
	motor[Leftside] = vexRT[Ch3];//////With the imput of the joysticks

	}



}

int gotoarm = 0; /////This int is not being used on purpose
																////////It is here to use the debug menu to quickly
																////////Navigate through the code by double clicking
task shooting()
{

	if (vexRT[Btn7U]==1 )
	{
		motor[Leftarm] = -127;
		motor[port6] = -127; //bottom left
		motor[Rightarm] = 127;
		motor[port9]= 127; //bottom right
	}
	else if (vexRT[Btn7D]==1 && SensorValue(in8)<2300)
	{
		motor[Leftarm] = 127;
		motor[port6]=127; //bottom left
		motor[Rightarm] = -127;
		motor[port9]= -127; //bottom right
		turnLEDOff(Yellow);
	}

	else if (vexRT[Btn7D]==1 && (SensorValue(in8)<4000 && SensorValue(in8)>2300))
	{
	turnLEDOn(Yellow);
		motor[Leftarm] = 30;
		motor[port6]=30; //bottom left
		motor[Rightarm] = -30;
		motor[port9]= -30;



	}

	else
	{
		motor[Leftarm] = 0;
		motor[port6] = 0; //bottom left
		motor[Rightarm] = 0;
		motor[port9] = 0; //bottom right
	}
}

int gotoclaw = 99;
//used to quickly navigate to claw code////


task theclaaaaawwww()
{
	if(vexRT[Btn6U]==1)
	{
		motor[claw] = 127; //left side claw
		motor[claw2] = 127; // right side claw
	}


	else if(vexRT[Btn5U]==1)
	{

		motor[claw] = -127; //left side claw
		motor[claw] = -127; //right side claw
	}

	else
	{
		motor[claw] = 0;
	}


}

int dumbquadencoderthignalisonwants;
 int gotointstuff = 0;

task intstuff()
{
	dumbquadencoderthignalisonwants = SensorValue(Leverangle);
	////////For testing if the encoder is working in the debug menu

	if(chooseautonomous==1) ////GREEN IS Leftside (Go right)
	{
		turnLEDOn(Green);
		turnLEDOff(Red);
	}

	else if(chooseautonomous==0)
	{
		turnLEDOn(Green);
		turnLEDOn(Red);
	}

	else
	{
		turnLEDOff(Green); ///RED IS rightside (go left)
		turnLEDOn(Red);

	}

}



task usercontrol()
{
	// User control code here, inside the loop //
	while(1==1)
	{
		///All the tasks run at the same time, to remove
	////Accidental priority with the code reading
	///Also it's easier to manage

		startTask (movement);
		startTask (shooting);
		startTask (theclaaaaawwww);
		startTask (intstuff);

	//	startTask (autonomousbutton);

	}
int stupidstorage = 0;

/*
old autonomous startup
motor(claw) = -30;
motor(claw2) = -30;  ///////SETUP SECTION///LENGTH: .15 SECODNS////

motor[Leftarm] = -85; //////This lifts arm so arm does not immediantly hit floor////
motor[port6] = -85; //bottom left
motor[Rightarm] = 85;
motor[port9]= 85; //bottom right

motor(Leftside) = -50; //////This moves us back slightly so arm doesnt hit stars
motor(Rightside) = -50;
*/

	/*
void autonomousexe2() /////////////OLD AUTONOMOUS/////////////////
{

	motor(Leftside) = 127;
	motor(Rightside) = 127;
	motor(Rightarm) = 35;
	motor(Leftarm) = -35;

	wait(2.4); /////This code simply moves forward and attempts to knock
						////// off a star

	motor(Leftside)=0;
	motor(Rightside) = 0;

	motor(Rightarm) = 0;
	motor(Leftarm) = 0;



	wait(3);
}
*/

















}
