#pragma config(Sensor, dgtl1,  leftswitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  rightswitch,    sensorTouch)
#pragma config(Motor,  port2,           Rightside,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           MiddleMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Leftside,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Rightlift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Leftlift1,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(300)
#pragma userControlDuration(900)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{ ////epic code//////////////
	////4ft in 2.5 sec//
      motor[Leftlift1] = -127;
 			motor[Rightlift1]= 127; //launch
 			wait(0.5);
 			motor[Rightside] = 127;
 			motor[Leftside] = 30;
 			wait (0.4);




////fin

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



int gotomovement = 6969;
	task movement()
	{

   motor[Rightside] = vexRT[Ch2];
   motor[Leftside] = vexRT[Ch3];


    if(vexRT[Btn6U]==1)
    {
    	motor[MiddleMotor]=64;
    }

    else if(vexRT[Btn6D]==1)
    {
   	motor[MiddleMotor]=127;
 		}

 		else if(vexRT[Btn5U]==1)
    {
   	motor[MiddleMotor]=-127;
 		}

 		else if(vexRT[Btn5D]==1)
    {
   	motor[MiddleMotor]=-64;
 		}

 		else
 		{
 			stopMotor(MiddleMotor);

 		}


  }

int gotoshooting = 1337;
 	task shooting()
	{

			if(vexRT[Btn8U]==1)
 		{
 			motor[Leftlift1] = -64;
 			motor[Rightlift1]= 64;

 		}

 		else if(vexRT[Btn8D]==1)
 		{
 			motor[Leftlift1] = -127;
 			motor[Rightlift1]= 127;
 		}

 		else
 		{
 			motor[Leftlift1] = 0;
 			motor[Rightlift1]= 0;
 		}

  }

  int leftswitchpress = 0;
  int rightswitchpress = 0;



  int gotoswitchtesting = 28795270251587957280158718093528731891580878791371389857879688828939587567187;
 task switchtest()
 {


   if(SensorValue(leftswitch)==1)
   {
     leftswitchpress = 1;
   }
   else
   {
     leftswitchpress = 0;
	 }

	 if(SensorValue(rightswitch)==1)
   {
     rightswitchpress = 1;
   }
   else
   {
     rightswitchpress = 0;
	 }

	}








int gotoimpliment = 10101010;
task usercontrol()
{
	// User control code here, inside the loop //
	while(1==1)
	{

		startTask (movement);



		startTask (shooting);
		startTask (switchtest);

	}


}

  /*if((vexRT[Btn5U]==1) || (vexRT[Btn5D]==1) || (vexRT[Btn6U]==1) || (vexRT[Btn6D]==1) ||
  	(vexRT[Ch3]>0) || (vexRT[Ch3]<0) || (vexRT[Ch4]>0) || (vexRT[Ch4]<0) || (vexRT[Ch1]>0) ||
 		(vexRT[Ch1]<0) || (vexRT[Ch2]>0) || (vexRT[Ch2]<0))*/







