#pragma config(Sensor, in1,    Clawthing,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Yes,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           Rightside,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Leftside,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw2,         tmotorVex393_MC29, openLoop) //right side claw
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop) // left side claw
#pragma config(Motor,  port6,           Leftarm2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Leftarm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rightarm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Rightarm2,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(300)
#pragma userControlDuration(900)
#include "Vex_Competition_Includes.c"   //Main competit
//ion background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

int gotoautonomous = 7;

//int autonomousside = 0     ;
/////0 = Go forward, go LEFT
/////1 = Go forward, go RIGHT

void autonomousexe()
{
/*
	motor(Leftside) = 127;
	motor(Rightside) = 127;
	motor(Rightarm) = 35;
	motor(Leftarm) = -35;

	wait(2.4);

	motor(Leftside)=0;
	motor(Rightside) = 0;

	motor(Rightarm) = 0;
	motor(Leftarm) = 0;



	wait(3);
}

task autonomous()
{ ////epic code//////////////
	////4ft in 2.5 sec//


autonomousexe();


	/*
	go forward
	score preload
	smack stars
	turn around
	score more stars





	////fin
	*/
}





/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
int clawangle = 10;

task movement()
{

	motor[Rightside] = vexRT[Ch2];
	motor[Leftside] = vexRT[Ch3];
/*
	if(vexRT[Btn6D]==1)
	{
		motor[MiddleMotor]=127;
	}

	else if(vexRT[Btn5D]==1)
	{
		motor[MiddleMotor]=-127;
	}

	else
	{
		stopMotor(MiddleMotor);
	}
	*/
}


task shooting()
{

	if (vexRT[Btn7U]==1)
	{
		motor[Leftarm] = -127;
		motor[port6] = -127; //bottom left
		motor[Rightarm] = 127;
		motor[port9]= 127; //bottom right
	}
	else if (vexRT[Btn7D]==1)
	{
		motor[Leftarm] = 127;
		motor[port6]=127; //bottom left
		motor[Rightarm] = -127;
		motor[port9]= -127; //bottom right
	}

	else
	{
		motor[Leftarm] = 0;
		motor[port6] = 0; //bottom left
		motor[Rightarm] = 0;
		motor[port9] = 0; //bottom right
	}
}

int gotoclaw = 99;
//used to quickly navigate to claw code////


task theclaaaaawwww()
{
	if(vexRT[Btn6U]==1)
	{
		motor[claw] = 127; //left side claw
		motor[claw2] = 127; // right side claw
	}


	else if(vexRT[Btn5U]==1)
	{

		motor[claw] = -127; //left side claw
		motor[claw] = -127; //right side claw
	}

	else
	{
		motor[claw] = 0;
	}


}
task intstuff()
{
	clawangle = SensorValue(Clawthing);

	if(clawangle<670)
	{
		turnLEDOn(Yes);
	}

	else
	{
		turnLEDOff(Yes);
	}
}

int useautonomousbutton = 1;
////1 to turn on, 0 to turn off
////(Actually, anything except 1 to turn off

int autonumber = 0;

task autonomousbutton()
{
	if(useautonomousbutton == 1)
	{
		if(vexRT[Btn8R]==1)
		{
			wait(0.5);
			if(vexRT[Btn8R]==1)
			{	autonumber = 1;
				autonomousexe();
				autonumber = 0;
			}
		}
	}
	else
	{
		autonumber = 0;
	}


}


task usercontrol()
{
	// User control code here, inside the loop //
	while(1==1)
	{

		while(autonumber==0)
		{
		startTask (movement);
		startTask (shooting);
		startTask (theclaaaaawwww);
		startTask (intstuff);
		}
		startTask (autonomousbutton);

	}


}
