#pragma config(Motor,  port2,           Leftarm,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Rightarm,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if (vexRT[Btn5U]==1)
		{
			motor[Leftarm] = -127;
			motor[Rightarm] = 127;
		}
		else if (vexRT[Btn5D]==1)
		{
			motor[Leftarm] = 127;
			motor[Rightarm] = -127;

		}
		else if (vexRT[Btn5D]==0)
	}

}
