#pragma config(Motor,  port2,           LaunchTop,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LaunchRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LaunchLeft,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	startMotor(LaunchTop, 127);
	startMotor(LaunchRight, 127);
	startMotor(LaunchLeft, 127);
	wait(1);
	stopMotor(LaunchLeft);
	stopMotor(LaunchRight);
	stopMotor(LaunchTop);

}
