#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  LED1,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  LED2,           sensorDigitalOut)
#pragma config(Sensor, I2C_1,  LeftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RightIEM,       sensorNone)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftLaunch,    tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           RightLaunch,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FrontIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Lift,          tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
/*#pragma autonomousDuration(20)
#pragma userControlDuration(120)*/

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

////////////////////////////////////////////////////////////////////////////////////////
//                                                                                    //
//                          Pre-Autonomous Functions                                  //
//                                   																								  //
// You may want to perform some actions before the competition starts. Do them in the //
// following function.																																//
//																																										//
////////////////////////////////////////////////////////////////////////////////////////

//Variable names and values
int fullcourtleft = 67;
int fullcourtright = 66;
int handload = 69;
int halfcourt = 64;
int autonpowerleft = 72;
int autonpowerright = 70;
int autonpowerleft1 = 70;
int autonpowerright1 = 69;

void linearMovement()
{
	//Linear movement code : Forward, Left, Right, and Back with left and right stick
	motor[RightMotor] = -vexRT[Ch2]; //RightMotor controlled with Ch2 on joystick
	motor[LeftMotor] = -vexRT[Ch3];  //LeftMotor controlled with Ch3 on joystick
}

void middleIntake ()
{
	//Intake turns forward if Btn5U is held down
	if(vexRT[Btn5U] == 1)
	{
		motor[Intake] = -100; //Intake turns at speed 100
	}

	//If Btn5U is not held down then Intake turns off
	else
	{
		motor[Intake] = 0; //Intake turns off
	}

	//Intake turns backward while Btn5D is held down
	while(vexRT[Btn5D] == 1)
	{
		motor[Intake] = 100; //Intake turns on at speed 100
	}
}

void foreIntake ()
{
	//FrontIntake turns towards driver if Btn6U is pressed
	while(vexRT[Btn6U] == 1)
	{
		motor[FrontIntake] = -127; //FrontIntake turns at full speed
	}

	//FrontIntake turns away from drive if Btn6D is pressed
	while(vexRT[Btn6D] == 1)
	{
		motor[FrontIntake] = 127; //FrontIntake turns at full speed
	}

	//FrontIntake turns off if Btn7R is pressed
	if(vexRT[Btn7R] == 1)
	{
		motor[FrontIntake] = 0; //FrontIntake turns off
	}
}

void launch ()
{
	//Both Launch motors spin at the same speed if Btn7U is pressed
	while(vexRT[Btn7U] == 1)
	{
		//Launch turns on at fullcourt speed
		motor[LeftLaunch] = fullcourtleft;
		motor[RightLaunch]	= fullcourtright;
	}

	//Launch turns off if Btn7L is pressed
	if(vexRT[Btn7L] == 1)
	{
		motor[LeftLaunch] = 0;
		motor[RightLaunch] = 0;
	}

	//Launch changes to handload speed if Btn8R is pressed
	while(vexRT[Btn8R] == 1)
	{
		motor[LeftLaunch] = handload;
		motor[RightLaunch] = handload;
	}

	//Launch changes to halfcourt speed if Btn 8U is pressed
	while(vexRT[Btn8U] == 1)
	{
		motor[LeftLaunch] = halfcourt;
		motor[RightLaunch] = halfcourt;
	}
}

void elevate ()
{
	if(vexRT[Btn7D] == 1)
	{
		motor[Lift] = 127;
	}
	else
	{
		motor[Lift] = 0;
	}
}

////////////////////////////////////////////SIT AND LAUNCH PROGRAM////////////////////////////////////////////////////////

void sitAndLaunch ()
{
	//Launch turns on at autonomous speed
	motor[LeftLaunch] = autonpowerleft1;
	motor[RightLaunch] = autonpowerright1;

	//Launch waits 3 seconds to rev up to full speed
	wait1Msec(3000);

	//Launch cycle repeats 3 times and shoots all 3 preloads
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000); 		//Wait 1 second
	motor[Intake] = 0;	//Intake turns off
	wait1Msec(1000);		//Wait 1 second

	motor[Intake] = 63;	//Intake turns on at half speed
	wait1Msec(1300);		//Wait 1 second
	motor[Intake] = 0;	//Intake turns off
	wait1Msec(1200);		//Wait 1 second

	motor[Intake] = 63;	//Intake turns on at half speed
	wait1Msec(1300);		//Wait 1 second
	motor[Intake] = 0;	//Intake turns off
	wait1Msec(1300);		//Wait 1 second

	//FrontIntake and Intake turn on to launch the fourth ball
	motor[FrontIntake] = 127;
	motor[Intake] = 63;
}

////////////////////////////////////////////BLUE RIGHT SIDE MIDFIELD PROGRAM///////////////////////////////////////////////

void blueRightMidfield ()
{
	//Launch turns on at autonomous speed
	motor[LeftLaunch] = autonpowerleft1;
	motor[RightLaunch] = autonpowerright1;

	//Launch waits 3 seconds to rev up to full speed
	wait1Msec(3000);

	//Launch cycle repeats 3 times and shoots 3 preloads
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000); 		//Wait 1 second
	motor[Intake] = 0;	//Intake turns off
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 0; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 0; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second

	motor[FrontIntake] = 127;

	motor[LeftMotor] = 63;
	motor[RightMotor] = -63;
	wait1Msec(00);

	motor[LeftMotor] = 63;
	motor[RightMotor] = 63;
	motor[Intake] = 63;
	wait1Msec(2000);

	motor[LeftMotor] = 63;
	motor[RightMotor] = -63;
	wait1Msec(500);
}

////////////////////////////////////////////BLUE LEFT SIDE MIDFIELD PROGRAM///////////////////////////////////////////////

void blueLeftMidfield ()
{

}

////////////////////////////////////////////RED RIGHT SIDE MIDFIELD PROGRAM///////////////////////////////////////////////

void redRightMidfield ()
{

}

////////////////////////////////////////////RED LEFT SIDE MIDFIELD PROGRAM////////////////////////////////////////////////

void redLeftMidfield ()
{
	//Launch turns on at autonomous speed
	motor[LeftLaunch] = autonpowerleft1;
	motor[RightLaunch] = autonpowerright1;

	//Launch waits 3 seconds to rev up to full speed
	wait1Msec(3000);

	//Launch cycle repeats 3 times and shoots 3 preloads
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000); 		//Wait 1 second
	motor[Intake] = 0;	//Intake turns off
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 0; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 63; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second
	motor[Intake] = 0; //Intake turns on at half speed
	wait1Msec(1000);		//Wait 1 second

	motor[FrontIntake] = 127;

	motor[LeftMotor] = 63;
	motor[RightMotor] = -63;
	wait1Msec(500);

	motor[LeftMotor] = 63;
	motor[RightMotor] = 63;
	motor[Intake] = 63;
	wait1Msec(2000);

	motor[LeftMotor] = -63;
	motor[RightMotor] = 63;
	wait1Msec(500);
}

////////////////////////////////////////////AUTONOMOUS CHALLENGE//////////////////////////////////////////////////////////

void autonomousChallenge ()
{
	motor[Lift] = 127;
	wait1Msec(10000000);

}

void autonomousChallenge2()
{
	//FrontIntake turns on at full speed
	motor[FrontIntake] = 127;

	//Launch turns on at autonomous speed
	motor[LeftLaunch] = autonpowerleft;
	motor[RightLaunch] = autonpowerright;

	//Intake turns on at half speed
	motor[Intake] = 63;

	//40 second time period for handloading on Blue Team square
	wait1Msec(10000000);
}

/////////////////////////////////////////////////METHODS END//////////////////////////////////////////////////////////////

void pre_auton()
{
}

///////////////////////////////////////////////////////////////////////////////////////////////
//																																													 //
//                                 Autonomous Task																					 //
//																																													 //
// This task is used to control your robot during the autonomous phase of a VEX Competition. //
//																																													 //
///////////////////////////////////////////////////////////////////////////////////////////////

task autonomous ()
{
	bLCDBacklight = true;	//Turn on LCD Backlight
	string mainBattery, backupBattery;

	sitAndLaunch();

	//autonomousChallenge();

	/*autonomousChallenge2();*/

	clearLCDLine(0);	//Clear line 1 (0) of the LCD
	clearLCDLine(1);	//Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');	//Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
	displayNextLCDString(backupBattery);

	//Short delay for the LCD refresh rate
	wait1Msec(10);
}

/////////////////////////////////////////////////////////////////////////////////////////////////
//																																														 //
//                                 User Control Task																					 //
//																																														 //
// This task is used to control your robot during the user control phase of a VEX Competition. //
//																																														 //
/////////////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	bLCDBacklight = true;	//Turn on LCD Backlight
	string mainBattery, backupBattery;

	while(1==1)
	{
		linearMovement();
		middleIntake();
		foreIntake();
		launch();
		elevate();

		clearLCDLine(0);	//Clear line 1 (0) of the LCD
		clearLCDLine(1);	//Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');	//Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(10);
	}
}
