#pragma config(Sensor, dgtl1,  led12,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  led11,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  led10,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  led9,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  led8,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  led7,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  led6,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  led5,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  led4,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, led3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, led2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, led1,           sensorLEDtoVCC)
#pragma config(Motor,  port2,           Backrightwheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Frontrightwheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Backleftwheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Frontleftwheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rightflywheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Leftflywheel,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
/*#pragma autonomousDuration(20)
#pragma userControlDuration(120)*/
int flywheelspeed = 62;

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

int click_to_autonomous = 0;

task autonomous()
{
	startMotor(Leftflywheel, 54);
	startMotor(Rightflywheel, 54);
	wait(2.5);
	startMotor(Intake, 127);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////
void ledees()
{
	switch (flywheelspeed)
	{
	case 50:   //case  < 33 doesn't work
	turnLEDOn(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;

	case  52:
turnLEDOff(led1);
turnLEDOn(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;

	case  54:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOn(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;

	case  56:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOn(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;
	case  58:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOn(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;
	case  60:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOn(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;
	case  62:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOn(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

		break;

case  64:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOn(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

			break;
case  66:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOn(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);

			break;
case  68:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOn(led10);
turnLEDOff(led11);
turnLEDOff(led12);

			break;
case  70:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOn(led11);
turnLEDOff(led12);

			break;
case  72:
turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOn(led12);

			break;
	default:
if(flywheelspeed>72)
{turnLEDOff(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOn(led12);
wait(0.3);
turnLEDOff(led12);
wait(0.3);
}

if(flywheelspeed<50)
{
	turnLEDOn(led1);
turnLEDOff(led2);
turnLEDOff(led3);
turnLEDOff(led4);
turnLEDOff(led5);
turnLEDOff(led6);
turnLEDOff(led7);
turnLEDOff(led8);
turnLEDOff(led9);
turnLEDOff(led10);
turnLEDOff(led11);
turnLEDOff(led12);
wait(0.3);
turnLEDOff(led1);
wait(0.3);
}
		break;
	}
}

task intakes ()// controller for intake runs as a seperate task
{
	if(vexRT[Btn6U]==1)
	{
		motor(Intake) = 127;
	}
	else if(vexRT[Btn6D]==1)
	{
		motor(Intake) = -127;
	}
	else
	{
		motor(Intake) = 0;
	}
}

task aimcontrol()
{
	/*if(vexRT[Btn5U]==1)
	{
	motor(Angler) = -40;
	}

	else
	{
	motor(Angler) = 0;
	}

	if(vexRT[Btn5D]==1 && SensorValue(Switch)==0) //when the button isnt pushed do this
	{
	motor(Angler) = 45;
	}
	else if(vexRT[Btn5D]==1 && SensorValue(Switch)==1)//when the switch is pressed down, the down button does nothing
	{
	motor(Angler) = 0;
	}

	*/

}




task basicflywheel()
{
	if(vexRT[Btn8U]==1)
	{
		while(vexRT[Btn8U]==1){}//DO NOTHING
		flywheelspeed=flywheelspeed+2;
	}
	else if(vexRT[Btn8D]==1)
	{
		while(vexRT[Btn8D]==1){}
		flywheelspeed=flywheelspeed-2;
	}
	else if(vexRT[Btn8L]==1)
	{
		while(vexRT[Btn8L]==1){}
		flywheelspeed=62;
	}
}

task usercontrol()//main task runs and starts sub tasks which run simultaneously
{
	turnLEDOn(led1);
	wait(1);
	turnLEDOff(led1);
	while(1==1)
	{

		ledees();

		if(vexRT[Btn8U]==1 || vexRT[Btn8D]==1 || vexRT[Btn8R]==1 || vexRT[Btn8L]==1)
		{//if the flywheel button is being used then run the flywheel code
			startTask(basicflywheel);

			if(vexRT[Btn8R]==1)
			{
				motor(Leftflywheel) = flywheelspeed - 10;
				motor(Rightflywheel) = flywheelspeed - 10;
			}
		}

		if(vexRT[Btn8U]==0 && vexRT[Btn8D]==0 && vexRT[Btn8R]==0 && vexRT[Btn8L]==0)
		{//if the flywheel button is not being used then turn off the led
			stopMotor(Rightflywheel);
			stopMotor(Leftflywheel);
		}

		if(vexRT[Ch2]>0 || vexRT[Ch2]<0 || vexRT[Ch3]>0 || vexRT[Ch3]<0)
		{//if the joysticks are moved, then run the drive code
			motor[Frontrightwheel] = vexRT[Ch2];
			motor[Backrightwheel] = vexRT[Ch2];
			motor[Frontleftwheel] = vexRT[Ch3];
			motor[Backleftwheel] = vexRT[Ch3];
		}

		if(vexRT[Ch2]==0 && vexRT[Ch2]==0 && vexRT[Ch3]==0 && vexRT[Ch3]==0)
		{//if the joysticks are not being moved, then turn off the led
	if(vexRT[Btn7L]==1)
		{
			motor(Backleftwheel) = 20;
			motor(Frontleftwheel) = 20;

			motor(Backrightwheel) = -20;
			motor(Frontrightwheel) = -20;

		}

		else if(vexRT[Btn7R]==1)
		{
			motor(Backleftwheel) = -20;
			motor(Frontleftwheel) = -20;

			motor(Backrightwheel) = 20;
			motor(Frontrightwheel)= 20;
		}
		else
		{
			stopMotor(Backleftwheel);
			stopMotor(Backrightwheel);
			stopMotor(Frontleftwheel);
			stopMotor(Frontrightwheel);
		}
		}



		if(vexRT[Btn5D]==1 || vexRT[Btn5U]==1)
		{//if the aim button is being pressed, then use the aim code
			startTask(aimcontrol);
		}

		if(vexRT[Btn6U]==1 || vexRT[Btn6D]==1)
		{//if the intakes are being used, then use the intake code
			startTask(intakes);
		}

		if(vexRT[Btn6U]==0 && vexRT[Btn6D]==0)
		{//if the intakes are not being used, then turn off the led
			stopMotor(Intake);
		}
	}
}
