#pragma config(Sensor, dgtl6,  Switch,         sensorTouch)
#pragma config(Sensor, dgtl10, GREEN,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, YELLOW,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, RED,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           Rightflywheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Leftflywheel,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Frontleftwheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Backleftwheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Frontrightwheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Backrightwheel, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Angler,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int shootmode = 1;
int flywheelon = 0;
int feedmodeon = 0;


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

	startMotor(Leftflywheel, 82);
	startMotor(Rightflywheel, 82);
	wait(4);
	startMotor(Intake, 127);
	wait(1);
	startMotor(Intake, 0);
	wait(4);
	startMotor(Intake, 127);
	wait(2);
	startMotor(Intake, 0);
	wait(1);
	startMotor(Intake, 127);
	wait(3);
	startMotor(Intake, 0);
	wait(1);
	startMotor(Intake, 127);
	wait(1);
	startMotor(Intake, 0);
	wait(1);
	startMotor(Intake, 127);
	wait(1);
	startMotor(Intake, 0);
	wait(1);
	startMotor(Intake, 127);
	wait(1);
	startMotor(Intake, 0);
	wait(1);
	startMotor(Intake, 127);
	wait(1);

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////






task intakes ()// controller for intake runs as a seperate task
{
	if(vexRT[Btn6U]==1)
	{
		motor(Intake) = 127;
	}
	else if(vexRT[Btn6D]==1)
	{
		motor(Intake) = -127;
	}
	else
	{
		motor(Intake) = 0;
	}

}





task AngleAdjust()
{

	if(vexRT[Btn5U]==1)
	{
		motor(Angler) = -45;
	}


	else
	{
		motor(Angler) = 0;
	}


	if(vexRT[Btn5D]==1 && SensorValue(Switch)==0) //when the button isnt pushed do this
	{
		motor(Angler) = 45;
	}
	else if(vexRT[Btn5D]==1 && SensorValue(Switch)==1)//when the switch is pressed down, the down button does nothing
	{
		motor(Angler) = 0;
	}


}



task feedmodecode()//toggles if the robot is being designed to shoot balls from home plate
{


	if(feedmodeon==0)
	{

		if(vexRT[Btn7U]==1)
		{

			motor(Leftflywheel) = 78;
			motor(Rightflywheel) = 78;

				if(vexRT[Btn7U]==0)
			{
				feedmodeon=1;
			}
		}
	}

	if(feedmodeon==1)
	{

		if(vexRT[Btn7U]==1)
		{

			motor(Leftflywheel) = 0;
			motor(Rightflywheel) = 0;

			if(vexRT[Btn7U]==0)
			{
				feedmodeon=0;
			}

		}
	}
}

////////////////////////////////////////////////////////////////////NOTIFICATIONS
task notifications()
{

	if(shootmode==0)
	{
		turnLEDOn(RED);
		turnLEDOff(GREEN);

	}

	if(shootmode==1)
	{
		turnLEDOn(GREEN);
		turnLEDOff(RED);
	}
	if(feedmodeon==1)
	{
		turnLEDOn(YELLOW);
	}
	if(feedmodeon==0)
	{
		turnLEDOff(YELLOW);
	}

}





//////////////////////////////////////////////////////
////////////////*****FLYWHEELCODE******////////////////////
/////////////////////////////////////////////////////

task flywheel()
{
	////////////TOGGLE MODE////////////////


		if(flywheelon==0)
		{
			if (vexRT[Btn7D]==1) //Press to change to press and hold mode
			{

				if(vexRT[Btn7D]==0)//activates when button is pushed and then let go
				{
				shootmode = 1;
				}

			}



			if(vexRT[Btn8U]==1)//High Button
			{
				motor(Leftflywheel) = 80;
				motor(Rightflywheel) = 80;

				if(vexRT[Btn8U]==0)
				{
					flywheelon = 1;
				}

			}

			if(vexRT[Btn8D]==1)//low botton
			{
				motor(Leftflywheel) = 40;
				motor(Rightflywheel) = 40;


				if(vexRT[Btn8D]==0)
				{
					flywheelon = 1;
				}

			}

			if(vexRT[Btn8R]==1)//medium high button
			{

				motor(Leftflywheel) = 75;
				motor(Rightflywheel) = 75;


				if(vexRT[Btn8R]==0)
				{
					flywheelon = 1;
				}

			}

			if(vexRT[Btn8L]==1)//medium low button
			{
				motor(Leftflywheel) = 64;
				motor(Rightflywheel) = 64;


				if(vexRT[Btn8L]==0)
				{
					flywheelon = 1;
				}

			}
		}

	/////////////////////////////////TOGGLE MODE CONTINUED/////////////////////
	if(flywheelon==1)
		{

		if (vexRT[Btn7D]==1) //Press to change to press and hold mode
		{

				if(vexRT[Btn7D]==0)//activates when button is pushed and then let go
				{
				shootmode = 1;
				}

		}

		if(vexRT[Btn8R]==1)//any button pushed again turns off motors
		{

			motor(Leftflywheel) = 0;
			motor(Rightflywheel) = 0;


				if(vexRT[Btn8R]==0)
				{
				flywheelon = 0;
				}

		}
		if(vexRT[Btn8U]==1)
		{

			motor(Leftflywheel) = 0;
			motor(Rightflywheel) = 0;


				if(vexRT[Btn8U]==0)
				{
				flywheelon = 0;
				}

		}
		if(vexRT[Btn8L]==1)
		{

			motor(Leftflywheel) = 0;
			motor(Rightflywheel) = 0;



				if(vexRT[Btn8L]==0)
				{
				flywheelon = 0;
				}

		}
		if(vexRT[Btn8D]==1)
		{

			motor(Leftflywheel) = 0;
			motor(Rightflywheel) = 0;


				if(vexRT[Btn8D]==0)
				{
				flywheelon = 0;
				}

			}
	}
}



	//////////////PRESS AND HOLD MODE///////////////////////////
task flywheel2()
{

		if (vexRT[Btn7D]==1) //Press to change to press and hold mode
		{

				if(vexRT[Btn7D]==0)//activates when button is pushed and then let go
				{
				shootmode = 0;
				}

		}

		if(vexRT[Btn8U]==1)
		{
			motor(Leftflywheel) = 82;
			motor(Rightflywheel) = 82;
		}
		else if(vexRT[Btn8D]==1)
		{
			motor(Leftflywheel) = 50;
			motor(Rightflywheel) = 50;
		}
		else if(vexRT[Btn8R]==1)
		{
			motor(Leftflywheel) = 75;
			motor(Rightflywheel) = 75;
		}
		else if(vexRT[Btn8L]==1)
		{
			motor(Leftflywheel) = 64;
			motor(Rightflywheel) = 64;
		}
		else
		{
			motor(Leftflywheel) = 0;
			motor(Rightflywheel) = 0;
		}
	}








task usercontrol()//main task runs and starts the many sub tasks which run simultaneously
{


	while(1==1)
	{

		motor[Frontleftwheel] = vexRT[Ch3];
		motor[Frontrightwheel] = vexRT[Ch2];

		startTask(notifications);


		motor[Backleftwheel] = vexRT[Ch3];
		motor[Backrightwheel] = vexRT[Ch2];

		startTask(feedmodecode);
	}

	while(vexRT[Ch2]>0 || vexRT[Ch2]<0 || vexRT[Ch3]>0 || vexRT[Ch3]<0)
	{//if the joysticks are moved, then run the drive code
		motor[Frontrightwheel] = vexRT[Ch2];
		motor[Backrightwheel] = vexRT[Ch2];
		motor[Frontleftwheel] = vexRT[Ch3];
		motor[Backleftwheel] = vexRT[Ch3];
	}


	while(shootmode==1)
	{


	startTask(flywheel2);

	}

	while(shootmode==0)
	{

	startTask(flywheel);

	}

	while(vexRT[Btn6U]==1 || vexRT[Btn6D]==1)
	{
		startTask(intakes);
	}



	while(vexRT[Btn5D]==1 || vexRT[Btn5U]==1)
	{
		startTask(AngleAdjust);
	}


	while(vexRT[Btn7L]==1 || vexRT[Btn7R]==1)
	{
		if(vexRT[Btn7L]==1)
		{
		motor[Frontrightwheel] = 30;
		motor[Backrightwheel] = 30;
		motor[Frontleftwheel] = -30;
		motor[Backleftwheel] = -30;

		}


	else if(vexRT[Btn7R]==1)
		{
		motor[Frontrightwheel] = -30;
		motor[Backrightwheel] = -30;
		motor[Frontleftwheel] = 30;
		motor[Backleftwheel] = 30;

		}
	else
		{
		motor[Frontrightwheel] = 0;
		motor[Backrightwheel] = 0;
		motor[Frontleftwheel] = 0;
		motor[Backleftwheel] = 0;

	}
	}


}






//NOTES TO SELF
//
//If the mode toggle doesnt work again be sure to make each mode a differant task and each button toggles wether which task runs or not
//
//
//
//
//
//
//
//
//
//
