#pragma config(Motor,  port2,           two,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           three,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           four,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           five,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           six,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           seven,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           eight,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           nine,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[two] = 63;
wait(1);
motor[three] = 63;
wait(1);
motor[four] = 63;
wait(1);
motor[five] = 63;
wait(1);
motor[six] = 63;
wait(1);
motor[seven] = 63;
wait(1);
motor[eight] = 63;
wait(1);
motor[nine] = 63;
wait(1);
motor[two] = 0;
motor[three] = 0;
motor[four] = 0;
motor[five] = 0;
motor[six] = 0;
motor[seven] = 0;
motor[eight] = 0;
motor[nine] = 0;

}
