#pragma config(Sensor, in1,    Gyro,           sensorNone)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    p,              sensorPotentiometer)
#pragma config(Sensor, in4,    h,              sensorLineFollower)
#pragma config(Sensor, in5,    g,              sensorReflection)
#pragma config(Sensor, dgtl1,  Jumper1,        sensorDigitalIn)
#pragma config(Sensor, dgtl2,  Jumper2,        sensorDigitalIn)
#pragma config(Sensor, dgtl3,  Jumper3,        sensorDigitalIn)
#pragma config(Sensor, dgtl4,  Jumper4,        sensorDigitalIn)
#pragma config(Sensor, dgtl5,  Jumper5,        sensorDigitalIn)
#pragma config(Sensor, dgtl6,  Quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  mobileGoal,     sensorDigitalOut)
#pragma config(Sensor, dgtl9,  mobileGoal2,    sensorDigitalOut)
#pragma config(Sensor, dgtl10, Quad2,          sensorQuadEncoder)
#pragma config(Motor,  port2,           leftside,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           bottom,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobile,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           fly,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightside,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           top,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/



int four;
/*task Quadreset()
{
SensorValue[Quad]=0;
SensorValue[Quad2]=0;
} */
void pre_auton()
{
	sensorvalue(potentiometer)=0;
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
task Quadreset()
{
	SensorValue[Quad]=0;
	SensorValue[Quad2]=0;
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	if(SensorValue[Jumper1]==0) //run if jumper in port 1
	{
		startTask(Quadreset);
		motor(bottom)=63;//lift
		motor(top)=63;//lift
		wait(1);
		motor(top)=0;//stoplift
		motor(bottom)=0;
		motor(mobile)=-127;//drop mobile
		wait(.8);
		motor(mobile)=0;//stop mobile
		while(SensorValue[Quad] < 230 || SensorValue[Quad2] < 230)
		{
			motor(leftside)=63;
			motor(rightside)=63; //drive to mobile
		}
		//startTask(Quadreset);

		//motor(leftside)=0;
		//motor(rightside)=0;//stop driving
		//while(SensorValue[Quad] < 100|| sensorValue[Quad2] < 100)
		//{
		//	motor(leftside)=63;
		//	motor(rightside)=63; //drive to mobile
		//}









		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;//stop drive
		motor(mobile)=127;//pick up mobile goal
		wait(.8);
		motor(mobile)=0;//stop mobile
		motor(top)=-30;
		motor(bottom)=-30;//drop lift
		wait(1);
		motor(top)=0;
		motor(bottom)=0;//stop drop lift
		motor(fly)=-127;//drop cone
		wait(.5);
		motor(fly)=0;//stop fly
		while(SensorValue[Quad] > -1300|| SensorValue[Quad2] > -1300)
		{
			motor(left)=-63;
			motor(rightside)=-63;
		}
		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;
		while( SensorValue[Quad] > -480 || SensorValue[Quad2] < 480)
		{

			motor(rightside)=63; // complete turn towards drop zone
		}
		startTask(Quadreset);
		while(SensorValue[Quad] < 60 || SensorValue[Quad2] < 60)
		{
			motor(leftside)=63; //drive to zone
		}
		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;
		motor(fly)=-127;
		wait(1);
		motor(fly);
		motor(mobile)=-127;// drop off mobile
		wait(.3);
		motor(mobile)=0;

		while(SensorValue[Quad] > -60 || SensorValue[Quad2] > -60)
		{
			motor(leftside)=-63; //back up
			motor(rightside)=-63;
		}
		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;
	}
	//left side
	{
		if(SensorValue[Jumper2]==0) //run if jumper in port 2
	{
		startTask(Quadreset);
		motor(bottom)=63;
		motor(top)=63;
		wait(1);
		motor(top)=0;
		motor(bottom)=0;
		motor(mobile)=-127;//pick up mobile
		wait(.8);
		motor(mobile)=0;
		while(SensorValue[Quad] < 100 || SensorValue[Quad2] < 100)
		{
			motor(leftside)=63;
			motor(rightside)=63; //drive to mobile
		}
		startTask(Quadreset);

		motor(leftside)=0;
		motor(rightside)=0;
		motor(top)=80;
		motor(bottom)=80;
		while(SensorValue[Quad] < 100|| sensorValue[Quad2] < 100)
		{
			motor(leftside)=63;
			motor(rightside)=63; //drive to mobile
			//dan sucks
		}
		startTask(Quadreset);
		wait(2); //pick up mobile and drop fly to drop cone
		motor(leftside)=0;
		motor(rightside)=0;
		motor(mobile)=127;
		wait(1.2);
		motor(mobile)=0;
		motor(top)=-63;
		motor(bottom)=-63
		wait(
		motor(fly)=-127;
		wait(1);
		motor(fly)=0;
		motor(top)=0;
		motor(bottom)=0;
		while(SensorValue[Quad] > -200|| SensorValue[Quad2] > -200)
		{
			motor(leftside)=-63;
			motor(rightside)=-63;
		}
		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;
		while( SensorValue[Quad] < 100)
		{

			motor(leftside)=63; // complete turn towards drop zone
		}
		startTask(Quadreset);
		while(SensorValue[Quad] < 60 || SensorValue[Quad2] < 60)
		{
			motor(leftside)=63; //drive to zone
		}
		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;

		motor(mobile)=-127;// drop off mobile
		wait(.3);
		motor(mobile)=0;

		while(SensorValue[Quad] > -60 || SensorValue[Quad2] > -60)
		{
			motor(leftside)=-63; //back up
			motor(rightside)=-63;
		}
		startTask(Quadreset);
		motor(leftside)=0;
		motor(rightside)=0;
	}
	//dan sucks at coding
	//dan has the big gay
	}
}
/////
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop Rhea is my best friend I hate everyone else


	four=1;
	while(1==1)
	{

		motor[rightside] = vexRT[Ch2];
		motor[leftside] = vexRT[Ch3];
		if(vexRT[Btn5UXmtr2]==1)
		{
			motor[fly]=127;
		}

		else if(vexRT[Btn5DXmtr2]==1)
		{
			motor[fly]=-127;

		}
		else
		{
			motor[fly]=0;
		}

		if(vexRT[Btn6UXmtr2]==1)
		{
			motor(top)=127;
			motor(bottom)=-127;
		}

		else if(vexRT[Btn6DXmtr2]==1)
		{
			motor(top)=-127;
			motor(bottom)=127;
		}
		else
		{
			motor(top)=0;
			motor(bottom)=0;
		}

		//Rhea is my best friend :)
		//elephants are great & Dan is a butt
		//zezak I don't know how to code
		//MobileGoalDown
		/*	if(vexRT[Btn7D]==1)
		{
		SensorValue[mobileGoal]=0;
		SensorValue[mobileGoal2]=0;

		}
		//MobileGoalUp
		if(vexRT[Btn7U]==1)
		{
		SensorValue[mobileGoal]=1;
		SensorValue[mobileGoal2]=1;
		}
		*/	if(vexRT[Btn8D]==1)
		{
			if(four==1)
			{
				motor(mobile)=-63;
				wait(.5);
				motor(mobile)=0;
				four=0;
			}
			else if(four==0)
			{
				motor(mobile)=63;
				wait(.8);
				motor(mobile)=0;
				four=1;
			}
			else
			{
				motor(mobile)=0;
			}
		}
		if(vexRT[Btn8R]==1)
		{

			motor(top)=127; //put lift up
			motor(bottom)=127;
			wait(1.2);//change
			motor(top)=50;
			motor(bottom)=50;
			motor(leftside)=127;
			motor(rightside)=127;
			wait(1);
			motor(leftside)=0;
			motor(rightside)=0;
			motor(fly)=-127;
			wait(1);
			motor(fly)=0;
		}
	}
}
