#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members:
Date:
Section:


Task Description:


Pseudocode:
If the light sensor detects an ambient light level of more than 275, turn the flashlight on.
*/

task main()
{
	while(1 ==1)
	{
		while(SensorValue(limitSwitch) == 1)
		{
			if(SensorValue(lightSensor)>275) //if the light sensor measures a light value of more than 275
			{
				turnFlashlightOn(flashlight,127); //turn the flash light on (at full power)
			}
			if(SensorValue(lightSensor)<=275) //if the light level is less than/equal to 275
			{
				turnFlashlightOff(flashlight); //turn the flashlight off
			}
		}
	}
}
