#pragma config(Sensor, in1,    clawPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           DriveLeft_1,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           DriveLeft_2,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           DriveRight_1,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           DriveRight_2,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armAngle,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify
#pragma platform(VEX2)
void pre_auton()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	SensorValue[solenoid] = 0;
}
task resetEverything() { //this is a subroutine that will reset the motors and encoders in one go
	motor[DriveLeft_1] = 0;
	motor[DriveLeft_2] = 0;
	motor[DriveRight_1] = 0;
	motor[DriveRight_2] = 0;
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
}

task resetMotors() { //this will stop all of the motors
	motor[DriveLeft_1] = 0;
	motor[DriveLeft_2] = 0;
	motor[DriveRight_1] = 0;
	motor[DriveRight_2] = 0;
}

task autonomous() {
	startTask(resetEverything); //start out by resetting all of the motors/sensors
	SensorValue[solenoid] = 0; //reset the pneumatics controller
	while(SensorValue[rightEncoder] > -220) { //move the robot slightly to the left in order to get a clear path
		motor[DriveRight_1] = 27;               //to the mobile goal
		motor[DriveRight_2] = 27;
	}
	startTask(resetEverything);
	while(SensorValue[rightEncoder] >-900 || SensorValue[leftEncoder] < 900) { //move the robot to the mobile goal
		motor[DriveLeft_1] = 63; //move at half speed
		motor[DriveLeft_2] = 63;
		motor[DriveRight_1] = 63;
		motor[DriveRight_2] = 63;
	}
	startTask(resetEverything);
	SensorValue[solenoid] = 1; //when the robot has reached the mobile goal, bring the pneumatics pistons up
	wait1Msec(1000); //wait 1 second
	while(SensorValue[leftEncoder] < -500 || SensorValue[rightEncoder] < 500) { //back out of the mobile goal area
		motor[DriveLeft_1] = -63;
		motor[DriveLeft_2] = -63;
		motor[DriveRight_1] = -63;
		motor[DriveRight_2] = -63;
	}
	startTask(resetEverything);

	while(SensorValue[leftEncoder] < 300 || SensorValue[rightEncoder] < 430) { //make a small turn to angle the robot
		motor[DriveLeft_1] = 63;                                                 //towards the scoring areas
		motor[DriveLeft_2] = 63;
		motor[DriveRight_1] = -63;
		motor[DriveRight_2] = -63;
	}
	startTask(resetMotors);
	while(SensorValue[leftEncoder] < -100 || SensorValue[rightEncoder] > 260) { //move the robot into the mobile goal area
		motor[DriveLeft_1] = 127;
		motor[DriveLeft_2] = 127;
		motor[DriveRight_1] = 127;
		motor[DriveRight_2] = 127;
	}
	startTask(resetEverything);
	while(SensorValue[rightEncoder] > -100 || SensorValue[leftEncoder] < 540) { //make another small adjustment
		motor[DriveLeft_1] = 63;
		motor[DriveLeft_2] = 63;
	}
	startTask(resetEverything);
	while(SensorValue[leftEncoder] < 350 || SensorValue[rightEncoder] > -350) { //run into the ten point scoring area
		motor[DriveLeft_1] = 127;
		motor[DriveLeft_2] = 127;
		motor[DriveRight_1] = 127;
		motor[DriveRight_2] = 127;
	}
	startTask(resetEverything);
	SensorValue[solenoid] = 0; //drop the pistons in order to score

	motor[DriveLeft_1] = -120; //back out of the scoring area for two seconds
	motor[DriveLeft_2] = -120;
	motor[DriveRight_1] = -120;
	motor[DriveRight_2] = -120;
	wait1Msec(2000);
	startTask(resetMotors); //stop all of the motors. In the competition template,
	//manual driver control takes over after this sequence
}

#define     JOY_DRIVE_V     vexJSLeftV
#define     JOY_DRIVE_H     vexJSLeftH
#define     JOY_THRESHOLD   15

#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 15      // Default will cause 4000mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    256     // essentially off
#define MOTOR_TASK_DELAY        20      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          10

// Array to hold requested speed for the motors
int motorReq[ MOTOR_NUM ];

// Array to hold "slew rate" for the motors, the maximum change every time the task
// runs checking current motor speed.
int motorSlew[ MOTOR_NUM ];


task MotorSlewRateTask()
{
	unsigned int motorIndex;
	int motorTmp;

	// Initialize crap
	for(motorIndex=0;motorIndex<MOTOR_NUM;motorIndex++)
	{
		motorReq[motorIndex] = 0;
		motorSlew[motorIndex] = MOTOR_DEFAULT_SLEW_RATE;
	}

	// run task until stopped
	while( true )
	{
		// run loop for every motor
		for( motorIndex=0; motorIndex<MOTOR_NUM; motorIndex++)
		{
			// So we don't keep accessing the internal storage
			motorTmp = motor[ motorIndex ];

			// Do we need to change the motor value ?
			if( motorTmp != motorReq[motorIndex] )
			{
				// increasing motor value
				if( motorReq[motorIndex] > motorTmp )
				{
					motorTmp += motorSlew[motorIndex];
					// limit
					if( motorTmp > motorReq[motorIndex] )
						motorTmp = motorReq[motorIndex];
				}

				// decreasing motor value
				if( motorReq[motorIndex] < motorTmp )
				{
					motorTmp -= motorSlew[motorIndex];
					// limit
					if( motorTmp < motorReq[motorIndex] )
						motorTmp = motorReq[motorIndex];
				}

				// finally set motor
				motor[motorIndex] = motorTmp;
			}
		}

		// Wait approx the speed of motor update over the spi bus
		wait1Msec( MOTOR_TASK_DELAY );
	}
}


void
DriveLeftMotor( int value )
{
	motorReq[ DriveLeft_1 ] = value;
	motorReq[ DriveLeft_2 ] = value;
}


void
DriveRightMotor( int value )
{
	motorReq[ DriveRight_1 ] = value;
	motorReq[ DriveRight_2 ] = value;
}


task ArcadeDrive()
{
	int    ctl_v;
	int    ctl_h;
	int    drive_l;
	int    drive_r;

	// Basic arcade control
	while( true )
	{
		// Get joystick H and V control
		ctl_v = vexRT[ JOY_DRIVE_V ];
		ctl_h = vexRT[ JOY_DRIVE_H ];

		// Ignore joystick near center
		if( (abs(ctl_v) <= JOY_THRESHOLD) && (abs(ctl_h) <= JOY_THRESHOLD) )
		{
			drive_l = 0;
			drive_r = 0;
		}
		else
		{
			// Create drive for left and right motors
			drive_l = (ctl_v + ctl_h) / 2;
			drive_r = (ctl_v - ctl_h) / 2;
		}

		// send out to motors
		DriveLeftMotor( drive_l );
		DriveRightMotor( drive_r );

		// Cortex is no bueno
		wait1Msec( 25 );
	}
}
task liftControl() {
	while(true) {
		motor[leftArm] = vexRT[Ch2]; //get input from the right side controller joystick and assign it to the left side arm
		motor[rightArm] = vexRT[Ch2];
		if(vexRT[Btn5U] == 1) { //if the left shoulder button is enabled
			motor[clawMotor] = -63;
		}
		else if (vexRT[Btn5D] == 1){
			motor[clawMotor] = 63;
		}
	}

	//	else if (vexRT[Btn5U] == 0) {
	//	while(SensorValue(clawPotentiometer) >= 100) {
	//	motor[clawMotor] = -63;
	//}
	//	}
}

task usercontrol()
{
	SensorValue(clawPotentiometer) = 0;
	// Start motor slew rate control
	startTask(MotorSlewRateTask);

	// Start driver control tasks
	startTask(ArcadeDrive);

	// Start driver lift control
	startTask(liftControl);

	// Everything done in other tasks
	while( true )
	{
		SensorValue[solenoid] = vexRT[Btn6U]; //pneumatics systems here
		wait1Msec( 100 );
	}
}
