#pragma config(Sensor, dgtl1,  Green1,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  Green2,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  Green3,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  Yellow1,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  Yellow2,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  Yellow3,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  Red1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, Red2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, Red3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, button,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Charge = nImmediateBatteryLevel;


task main()
{

	while(1==1)
	{
		int BTLH;

		int BL = nImmediateBatteryLevel;

		if(SensorValue(button)==1)
		{/*








			GREENS = Value of 1 (+5)

			YELLOWS = Value of .2

			REDS = Value of .1

			Ex.
			2 Green
			2 yellow
			1 red
			=
			7.5 Volts
			*/


			if(BL>7999) //8 volts
			{//BTLH = Battery level in hundreths
				BTLH = BL - 8000;
			}
			else if(BL>5999 && BL < 7000) //6 volts
			{
				BTLH = BL-6000;
			}

			else
			{
				BTLH = BL - 7000;
			}
			/*if the code sents out say; 7857
			subtract by 7000 and you get 857
			the code will read that number and will always be between
			999 or 001

			*/

			if(BTLH < 100)/////less than .1 volts, so if its ex. 8.0 volts
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOff(Red3);
				turnLEDOff(Yellow1);
				turnLEDOff(Yellow2);
				turnLEDOff(Yellow3);
				if(BTLH < 100 && BTLH > 50)////8.06
				{
					wait(0.4);
					turnLEDOn(Red2);
					wait(0.4);

				}
			}

			if(BTLH > 99 && BTLH <200)//// .1
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOn(Red3);
				turnLEDOff(Yellow1);
				turnLEDOff(Yellow2);
				turnLEDOff(Yellow3);

				if(BTLH > 99 && BTLH < 151)////.15
				{
					wait(0.4);
					turnLEDOff(Red3);
					wait(0.4);
				}

			}
			if(BTLH >199 && BTLH <300)///.2
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOff(Red3);
				turnLEDOff(Yellow1);
				turnLEDOff(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH > 199 && BTLH < 251)///.25
				{
					wait(0.4);
					turnLEDOff(Yellow3);
					wait(0.4);
				}

			}

			if(BTLH > 299 && BTLH < 400)///.3
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOn(Red3);
				turnLEDOff(Yellow1);
				turnLEDOff(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH>299 && BTLH < 351)
				{
					wait(0.4);
					turnLEDOff(Red3);

					wait(0.4);
				}
			}
			if(BTLH > 399 && BTLH < 500) ////.4
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOff(Red3);
				turnLEDOff(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH > 399 && BTLH <451)
				{
					wait(0.4);
					turnLEDOff(Yellow2);

					wait(0.4);
				}
			}

			if(BTLH > 499 && BTLH < 600) ///.5
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOn(Red3);
				turnLEDOff(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH > 499 && BTLH <551)
				{
					wait(0.4);
					turnLEDOff(Red3);

					wait(0.4);
				}
			}

			if(BTLH > 599 && BTLH < 700) ////.6
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOff(Red3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH > 599 && BTLH < 651)
				{
					wait(0.4);
					turnLEDOff(Yellow1);

					wait(0.4);
				}
			}
			if(BTLH > 699 && BTLH < 800) /////.7
			{
				turnLEDOff(Red1);
				turnLEDOff(Red2);
				turnLEDOn(Red3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH > 699 && BTLH < 751)//////.75
				{
					wait(0.4);
					turnLEDOff(Red3);
					wait(0.4);

				}
			}
			if(BTLH > 799 && BTLH <900) /////.8
			{
				turnLEDOff(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);

				if(BTLH > 799 && BTLH <851)//////.85
				{
					wait(0.4);
					turnLEDOff(Red2);
					wait(0.4);
				}
			}
			if(BTLH >899 && BTLH <1000)///////.9
			{
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);
				if(BTLH > 899 && BTLH <951)///////.95
				{
					wait(0.4);
					turnLEDOff(Red1);
					wait(0.4);
				}

			}

			if(BL>7999)///8
			{
				turnLEDOn(Green1);
				turnLEDOn(Green2);
				turnLEDOn(Green3);
			}

			if(BL>6999 && BL <8000)///7
			{
				turnLEDOff(Green1);
				turnLEDOn(Green2);
				turnLEDOn(Green3);
			}
			if(BL<7000)
			{turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOn(Green3);
			}

		}


		if(SensorValue(button)==0)
		{


////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////// ORIGINAL    /////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////



			if(BL>8399)
			{


				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);
				turnLEDOff(Green3);
				wait(0.20);
				turnLEDOff(Green2);
				wait(0.20);
				turnLEDOff(Green1);
				wait(0.18);
				turnLEDOn(Green3);
				wait(0.20);
				turnLEDOn(Green2);
				wait(0.20);
				turnLEDOn(Green1);
				wait(0.20);

			}





			if(8400>BL && BL>8000)
			{

				turnLEDOn(Green1);
				turnLEDOn(Green2);
				turnLEDOn(Green3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);
				if(8100>BL && BL>8000)
				{
					wait(0.1);
					turnLEDOff(Green1);
					wait(0.1);
				}

			}

			if(8001>BL && BL>7600)
			{

				turnLEDOff(Green1);
				turnLEDOn(Green2);
				turnLEDOn(Green3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);
				if(7700>BL && BL>7600)
				{
					wait(0.1);
					turnLEDOff(Green2);
					wait(0.1);

				}
			}

			if(7601>BL && BL>7349)
			{

				turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOn(Green3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);


			}

			if(7350>BL && BL>7199)
			{

				turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOn(Green3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				wait(0.1);
				turnLEDOff(Green3);
				wait(0.1);


			}
			if(7200>BL && BL>7099)
			{

				turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOff(Green3);
				turnLEDOn(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Yellow3);
				turnLEDOn(Red1);
				turnLEDOn(Red2);
				turnLEDOn(Red3);



			}


			if(7100>BL && BL>6900)
			{

				turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOff(Green3);
				turnLEDOff(Yellow1);
				turnLEDOn(Yellow2);
				turnLEDOn(Red1);
				turnLEDOn(Red2);

			}


			if(6901>BL && BL>6699)
			{

				turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOff(Green3);
				turnLEDOff(Yellow1);
				turnLEDOff(Yellow2);
				turnLEDOn(Red1);
				turnLEDOn(Red2);

			}


			if(6700>BL)
			{

				turnLEDOff(Green1);
				turnLEDOff(Green2);
				turnLEDOff(Green3);
				turnLEDOff(Yellow1);
				turnLEDOff(Yellow2);
				turnLEDOff(Red1);
				turnLEDOn(Red2);

			}

		}

}}
