#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl2,  NoSensor,       sensorDigitalOut)
#pragma config(Sensor, dgtl7,  BackEN,         sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  LeftClaw,       sensorDigitalOut)
#pragma config(Sensor, dgtl10, RightClaw,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, RightEN,        sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  FrontEN,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RightLiftEN,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  BackEN,         sensorNone)
#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightMotor,    tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl11)
#pragma config(Motor,  port4,           BackMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FrontMotor,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port6,           Lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Lift2,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           Lift1b,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Lift2b,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)

//////////////Blue Cube and Skyrise Program////////////////////////////////////////////
task main()
{




//Put in the cube
while(SensorValue[RightEN]>-85)
{
	motor(LeftMotor)=-127;
	motor(RightMotor)=-127;
}
	motor(LeftMotor)=0;
	motor(RightMotor)=0;
	wait1Msec(100);

















//Close the claw
SensorValue[RightClaw]=1;
wait1Msec(100);

//Open the claw
SensorValue[RightClaw]=0;
wait1Msec(100);

//Close the claw
SensorValue[RightClaw]=1;
wait1Msec(100);
























//Lift up goes to grab skyrise
while(SensorValue[FrontEN]<900)
{
	motor(Lift1)=127;
	motor(Lift2)=127;
	motor(Lift1b)=127;
	motor(Lift2b)=127;

	//Open the claw
	SensorValue[RightClaw]=0;

}
	motor(Lift1)=0;
	motor(Lift2)=0;
	motor(Lift1b)=0;
	motor(Lift2b)=0;
wait1Msec(75);




















//Move to grab skyrise
	while(SensorValue[BackEN]<85)
{
	motor(BackMotor)=127;
	motor(FrontMotor)=127;
}
	motor(FrontMotor)=0;
	motor(BackMotor)=0;
wait1Msec(75);









//Close the claw
SensorValue[RightClaw]=1;
wait1Msec(75);










//Lift up further
while(SensorValue[FrontEN]<2200)
{
	motor(Lift1)=127;
	motor(Lift2)=127;
	motor(Lift1b)=127;
	motor(Lift2b)=127;
}
	motor(Lift1)=0;
	motor(Lift2)=0;
	motor(Lift1b)=0;
	motor(Lift2b)=0;
wait1Msec(75);











//Rotate to align with skyrise drop
while(SensorValue[BackEN]<332)
	{
		motor(LeftMotor)=127;
		motor(RightMotor)=-127;
		motor(FrontMotor)=-127;
		motor(BackMotor)=127;
	}
		motor(LeftMotor)=0;
		motor(RightMotor)=0;
		motor(FrontMotor)=0;
		motor(BackMotor)=0;
wait1Msec(75);




/*

/*
//Slight movement to the right //-20 to 12
while(SensorValue[BackEN]<-10)
{

	motor(FrontMotor)=127;
	motor(BackMotor)=127;
	wait1Msec(210);
	motor(FrontMotor)=0;
	motor(BackMotor)=0;
wait1Msec(100);

*/









//Lift goes down
while(SensorValue[FrontEN]>750)
{
	motor(Lift1)=-127;
	motor(Lift2)=-127;
	motor(Lift1b)=-127;
	motor(Lift2b)=-127;
}
	motor(Lift1)=0;
	motor(Lift2)=0;
	motor(Lift1b)=0;
	motor(Lift2b)=0;
wait1Msec(75);









//Open the claw
SensorValue[RightClaw]=0;
wait1Msec(75);








//////////////////////////////////////second skyrise program............................


//Lift up further
while(SensorValue[FrontEN]<1200)
{
	motor(Lift1)=127;
	motor(Lift2)=127;
	motor(Lift1b)=127;
	motor(Lift2b)=127;
}
	motor(Lift1)=0;
	motor(Lift2)=0;
	motor(Lift1b)=0;
	motor(Lift2b)=0;
wait1Msec(75);








//Rotate back to align with skyrise pickup
while(SensorValue[BackEN]>239)
	{
		motor(LeftMotor)=-60;
		motor(RightMotor)=60;
		motor(FrontMotor)=60;
		motor(BackMotor)=-60;
	}
		motor(LeftMotor)=0;
		motor(RightMotor)=0;
		motor(FrontMotor)=0;
		motor(BackMotor)=0;
wait1Msec(1350);//change to 1350











//Close the claw
SensorValue[RightClaw]=1;
wait1Msec(125);












//Lift up further
while(SensorValue[FrontEN]<3000)
{
	motor(Lift1)=127;
	motor(Lift2)=127;
	motor(Lift1b)=127;
	motor(Lift2b)=127;
}
	motor(Lift1)=0;
	motor(Lift2)=0;
	motor(Lift1b)=0;
	motor(Lift2b)=0;
wait1Msec(75);






















//Rotate to align with skyrise drop
while(SensorValue[BackEN]<355)
	{
		motor(LeftMotor)=127;
		motor(RightMotor)=-127;
		motor(FrontMotor)=-127;
		motor(BackMotor)=127;
	}
		motor(LeftMotor)=0;
		motor(RightMotor)=0;
		motor(FrontMotor)=0;
		motor(BackMotor)=0;
wait1Msec(75);













//Lift goes down
while(SensorValue[FrontEN]>1350)
{
	motor(Lift1)=-127;
	motor(Lift2)=-127;
	motor(Lift1b)=-127;
	motor(Lift2b)=-127;
}
	motor(Lift1)=0;
	motor(Lift2)=0;
	motor(Lift1b)=0;
	motor(Lift2b)=0;
wait1Msec(75);








//Open the claw
SensorValue[RightClaw]=0;
wait1Msec(75);





}
