#pragma config(Sensor, in1,    LeftEncoder,    sensorNone)
#pragma config(Sensor, dgtl1,  LeftEn,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEn,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LeftLiftEN,     sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  RightLiftEN,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Solenoid1,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  RightLiftEn,    sensorNone)
#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port3,           Left2,         tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port4,           Left3,         tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port5,           Right1,        tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, dgtl3)
#pragma config(Motor,  port6,           Right2,        tmotorVex393_MC29, openLoop, driveRight, encoderPort, dgtl3)
#pragma config(Motor,  port7,           Right3,        tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, dgtl3)
#pragma config(Motor,  port8,           LeftLift,      tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl5)
#pragma config(Motor,  port9,           RightLift,     tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, dgtl7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(1==1)
{

		motor(Left1) = vexRT[Ch3];
		motor(Left2) = vexRT[Ch3];
		motor(Left3) = vexRT[Ch3];
		motor(Right1) = vexRT[Ch2];
		motor(Right2) = vexRT[Ch2];
		motor(Right3) = vexRT[Ch2];

	if(vexRT[Btn5U]==1)
	{
		motor(LeftLift)=127;
		motor(RightLift)=127;
	}
	else if(vexRT[Btn5D]==1)
	{
		motor(RightLift)=-127;
		motor(LeftLift)=-127;
	}
	else
	{
		motor(RightLift)=0;
		motor(LeftLift)=0;
	}

//press button for exact level
while(vexRT[Btn6D]==1)
{
	if(SensorValue[LeftLiftEN]>-15)
	{
		motor(LeftLift)=127;
		motor(RightLift)=127;
		motor(Left1) = vexRT[Ch3];
		motor(Left2) = vexRT[Ch3];
		motor(Left3) = vexRT[Ch3];
		motor(Right1) = vexRT[Ch2];
		motor(Right2) = vexRT[Ch2];
		motor(Right3) = vexRT[Ch2];
	}
	else if(SensorValue[LeftLiftEN]<-15)
	{
		motor(LeftLift)=-127;
		motor(RightLift)=-127;
		motor(Left1) = vexRT[Ch3];
		motor(Left2) = vexRT[Ch3];
		motor(Left3) = vexRT[Ch3];
		motor(Right1) = vexRT[Ch2];
		motor(Right2) = vexRT[Ch2];
		motor(Right3) = vexRT[Ch2];
	}
	else
	{
		motor(LeftLift)=0;
		motor(RightLift)=0;
		motor(Left1) = vexRT[Ch3];
		motor(Left2) = vexRT[Ch3];
		motor(Left3) = vexRT[Ch3];
		motor(Right1) = vexRT[Ch2];
		motor(Right2) = vexRT[Ch2];
		motor(Right3) = vexRT[Ch2];
	}
}
}
}
