#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LineFLeft,      sensorLineFollower)
#pragma config(Sensor, in2,    LineFCenter,    sensorLineFollower)
#pragma config(Sensor, in3,    LineFRight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  UltraSens,      sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           claw2,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightFrontMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           LeftFrontMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           LeftBackMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LiftR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!....HA HA HA....I did modify...LOL..

/////////////////////////////////////////////////////////////////////////////////////////








/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////






/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	motor(claw) = -100;
	motor(claw2) = -100;

	wait1Msec(500);


	motor(RightBackMotor) = -100;
	motor(RightFrontMotor) = -100;
	motor(LeftBackMotor) = -100;
	motor(LeftFrontMotor) = -100;

	wait1Msec(2000);

}

/////////////////////////////////////////////////////////////////////////////////////////







/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

		while(1==1)
	{


		motor(LeftBackMotor)=vexRT(Ch3);
		motor(LeftFrontMotor)= vexRT(Ch3);
		motor(RightFrontMotor) = vexRT(Ch2);
		motor(RightBackMotor) = vexRT(Ch2);


		if(vexRT[Btn8R] == 1)
		{
			motor(claw) = 100;
			motor(claw2) = 100;
		}

		else if(vexRT[Btn8L] == 1)
		{
			motor(claw) = -50;
			motor(claw2) = -50;
		}

		if(vexRT[Btn8U] == 1)
		{
				motor(LiftL) = 200;
				motor(LiftR) = 200;
		}
		else if(vexRT[Btn8D] == 1)
		{
				motor(LiftL) = -200;
				motor(LiftR) = -200;
		}

		else
		{
			motor(claw) = 0;
			motor(claw2) = 0;
			motor(LiftL) = 0;
			motor(LiftR) = 0;
		}

	}


}
