#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl12, Speaker,        sensorDigitalOut)
#pragma config(Sensor, I2C_1,  FrontEN,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RightLiftEN,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BackMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FrontMotor,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port6,           Lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Lift2,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           Manip1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Manip2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//Methods:


void RemoteControl()
{
	while(1==1)
	{

//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

//Lift control: use buttons 5D and 5U to move up and down
	if(vexRT[Btn5U]==1)
	{
		//if(SensorValue[FrontEN]<9400 || vexRT[Btn7U]==1)
		//{
			motor(Lift1)=127;
			motor(Lift2)=127;
		//}
		//else
		//{
			motor(Lift1)=0;
			motor(Lift2)=0;
		//}
	}
	else if(vexRT[Btn5D]==1)
	{
		//if(SensorValue[FrontEN]>0 || vexRT[Btn7D]==1)
		//{
			motor(Lift1)=-127;
			motor(Lift2)=-127;
		//}
		//else
		//{
			motor(Lift1)=0;
			motor(Lift2)=0;
		//}
	}
	else
	{
		motor(Lift1)=0;
		motor(Lift2)=0;
	}

//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}
	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}

//Button to level program encoder value = 1900 (skyrise pickup height)
if(vexRT(Btn7L) == 1){
	while(SensorValue(FrontEN) < 1900 && (vexRT(Btn8R) == 0)){
		motor(Lift1) = 127;
		motor(Lift2) = 127;

		//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

	//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}
	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}
	}

	while(SensorValue(FrontEN) > 2000 && (vexRT(Btn8R) == 0)) {
		motor(Lift1) = -127;
		motor(Lift2) = -127;

		//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

	//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}
	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}
	}
}


//Button that lifts to cube height,
if(vexRT(Btn8L) == 1){
	while(SensorValue(FrontEN) < 3050 && (vexRT(Btn8R) == 0)){
		motor(Lift1) = 127;
		motor(Lift2) = 127;

		//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

	//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}
	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}
	}

	while(SensorValue(FrontEN) > 3050 && (vexRT(Btn8R) == 0)) {
		motor(Lift1) = -127;
		motor(Lift2) = -127;

		//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

	//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}

	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}
	}
}







//skyrise deposit height
//Button that lifts to skyrise cube height,               6300 = cube on syrise height. = Btn 7R
if(vexRT(Btn7R) == 1){
	while(SensorValue(FrontEN) < 6294 && (vexRT(Btn8R) == 0)){
		motor(Lift1) = 127;
		motor(Lift2) = 127;

		//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

	//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}
	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}
	}

	while(SensorValue(FrontEN) > 6294 && (vexRT(Btn8R) == 0)) {
		motor(Lift1) = -127;
		motor(Lift2) = -127;

		//Linear movement code : Forward, Left, Right, and Back with left stick
		motor(LeftMotor)=-vexRT[Ch3];
		motor(RightMotor)=-vexRT[Ch3];
		motor(FrontMotor)=vexRT[Ch4];
		motor(BackMotor)=vexRT[Ch4];

//Rotation movement code: When 6D is pressed, move right joystick left and right to rotate left and right
	while(vexRT[Btn6D]==1)
	{
		motor(LeftMotor)=-vexRT[Ch1];
		motor(RightMotor)=vexRT[Ch1];
		motor(FrontMotor)=vexRT[Ch1];
		motor(BackMotor)=-vexRT[Ch1];
	}

	//Manipulation: Use buttons 8D and 8U to move the manipulator forward and backward
	if(vexRT[Btn8D]==1)
	{
		motor(Manip1)=127;
		motor(Manip2)=127;
		playSound(soundDownwardTones);
	}
	else if(vexRT[Btn8U]==1)
	{
		motor(Manip1)=-127;
		motor(Manip2)=-127;
		playSound(soundFastUpwardTones);
	}
	else
	{
		motor(Manip1)=0;
		motor(Manip2)=0;
	}
	}
}

}
}





/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
SensorValue[FrontEN]=0;
}
/////////////////////////////////////////////////////////////////////////////////////////




/////////////////////////////////////////////////////////////////////////////////////////////
task autonomous()
{

SensorValue[FrontEN]=0;



//Put the cube in the nub
motor(LeftMotor)=-127;
motor(RightMotor)=-127;
wait1Msec(285);
motor(LeftMotor)=0;
motor(RightMotor)=0;
wait1Msec(100);



//skyrise auton

//shake the manipulator fold off
motor(FrontMotor)=-127;
motor(BackMotor)=-127;
wait1Msec(150);
motor(FrontMotor)=127;
motor(BackMotor)=127;
wait1Msec(150);
motor(FrontMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);


//Lift to skyrise pull altitude
while(SensorValue[FrontEN]<2400)
{
	motor(Lift1)=127;
	motor(Lift2)=127;
}
motor(Lift1)=0;
motor(Lift2)=0;


//move and grab skyrise
motor(FrontMotor)=-80;
motor(BackMotor)=-80;
wait1Msec(575);
motor(FrontMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);

//Lift up to higher altitude with the skyrise
motor(Lift1)=127;
motor(Lift2)=127;
wait1Msec(2300);
motor(Lift1)=0;
motor(Lift2)=0;
wait1Msec(100);

//Backup to orginial spot
motor(FrontMotor)=127;
motor(BackMotor)=127;
wait1Msec(560);
motor(FrontMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);

//Rotate to align with skyrise nub

motor(LeftMotor)=-127;
motor(RightMotor)=127;
motor(FrontMotor)=127;
motor(BackMotor)=-127;
wait1Msec(357);
motor(LeftMotor)=0;
motor(RightMotor)=0;
motor(FrontMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);


//Move torwards to skyrise nub
motor(FrontMotor)=-127;
motor(BackMotor)=-127;
wait1Msec(269);
motor(FrontMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);


//put the skyrise back
while(SensorValue[FrontEN]>285)
{
	motor(Lift1)=-127;
	motor(Lift2)=-127;
}
motor(Lift1)=0;
motor(Lift2)=0;
wait1Msec(240);

//wiggle
motor(LeftMotor)=127;
motor(FrontMotor)=127;
motor(RightMotor)=-127;
motor(BackMotor)=-127;
wait1Msec(250);
motor(LeftMotor)=0;
motor(FrontMotor)=0;
motor(RightMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);
motor(LeftMotor)=-127;
motor(FrontMotor)=-127;
motor(RightMotor)=127;
motor(BackMotor)=127;
wait1Msec(250);
motor(LeftMotor)=127;
motor(FrontMotor)=0;
motor(RightMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);



//Move away from skyrise
motor(FrontMotor)=127;
motor(BackMotor)=127;
wait1Msec(650);
motor(FrontMotor)=0;
motor(BackMotor)=0;
wait1Msec(100);


}
/////////////////////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////
task usercontrol()
{
	RemoteControl();
}
/////////////////////////////////////////////////////////////////////////////////////////////
