#pragma config(Motor,  port2,           mDriveL,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           mDriveL2,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           mDriveR,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           mDriveR2,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           liftControl,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           liftControl1,  tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify
#pragma platform(VEX2)

void pre_auton() {
}
task autonomous() {
	motor[mDriveL] = 127;
	motor[mDriveR] = 127;
	motor[mDriveL2] = 127;
	motor[mDriveR2] = 127;
	wait(10);
	motor[mDriveL] = 0;
	motor[mDriveL2] = 0;
	motor[mDriveR] = 0;
	motor[mDriveR2] = 0;
}


#define     JOY_DRIVE_V     vexJSLeftV
#define     JOY_DRIVE_H     vexJSLeftH
#define     JOY_THRESHOLD   15

#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 10      // Default will cause 375mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    256     // essentially off
#define MOTOR_TASK_DELAY        15      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          10

// Array to hold requested speed for the motors
int motorReq[ MOTOR_NUM ];

// Array to hold "slew rate" for the motors, the maximum change every time the task
// runs checking current motor speed.
int motorSlew[ MOTOR_NUM ];


task MotorSlewRateTask()
{
	unsigned int motorIndex;
	int motorTmp;

	// Initialize crap
	for(motorIndex=0;motorIndex<MOTOR_NUM;motorIndex++)
	{
		motorReq[motorIndex] = 0;
		motorSlew[motorIndex] = MOTOR_DEFAULT_SLEW_RATE;
	}

	// run task until stopped
	while( true )
	{
		// run loop for every motor
		for( motorIndex=0; motorIndex<MOTOR_NUM; motorIndex++)
		{
			// So we don't keep accessing the internal storage
			motorTmp = motor[ motorIndex ];

			// Do we need to change the motor value ?
			if( motorTmp != motorReq[motorIndex] )
			{
				// increasing motor value
				if( motorReq[motorIndex] > motorTmp )
				{
					motorTmp += motorSlew[motorIndex];
					// limit
					if( motorTmp > motorReq[motorIndex] )
						motorTmp = motorReq[motorIndex];
				}

				// decreasing motor value
				if( motorReq[motorIndex] < motorTmp )
				{
					motorTmp -= motorSlew[motorIndex];
					// limit
					if( motorTmp < motorReq[motorIndex] )
						motorTmp = motorReq[motorIndex];
				}

				// finally set motor
				motor[motorIndex] = motorTmp;
			}
		}

		// Wait approx the speed of motor update over the spi bus
		wait1Msec( MOTOR_TASK_DELAY );
	}
}
void DriveLeftMotor (int value) {
	motorReq[mDriveL] = value;
	motorReq[mDriveL2] = value;
}

void
DriveRightMotor( int value )
{
	motorReq[ mDriveR ] = value;
	motorReq[ mDriveR2 ] = value;
}

task ArcadeDrive()
{
	int    ctl_v;
	int    ctl_h;
	int    drive_l;
	int    drive_r;

	// Basic arcade control
	while( true )
	{
		// Get joystick H and V control
		ctl_v = vexRT[ JOY_DRIVE_V ];
		ctl_h = vexRT[ JOY_DRIVE_H ];

		// Ignore joystick near center
		if( (abs(ctl_v) <= JOY_THRESHOLD) && (abs(ctl_h) <= JOY_THRESHOLD) )
		{
			drive_l = 0;
			drive_r = 0;
		}
		else
		{
			// Create drive for left and right motors
			drive_l = (ctl_v + ctl_h) / 2;
			drive_r = (ctl_v - ctl_h) / 2;
		}

		// send out to motors
		DriveLeftMotor( drive_l );
		DriveRightMotor( drive_r );

		// Cortex is no bueno
		wait1Msec( 25 );
	}
}
//task liftControl() {
	//while(true) {
//	motor[liftLeft] = vexRT[Ch2Xmtr2];
	//motor[liftRight] = vexRT[Ch3Xmtr2];
//}
//}

task usercontrol() {
	while (true) {
	//startTask(MotorSlewRateTask);
	//startTask(ArcadeDrive);


	motor[mDriveL] = vexRT[Ch2];
	motor[mDriveL2] = vexRT[Ch2];
	motor[mDriveR] = vexRT[Ch3];
	motor[mDriveR2] = vexRT[Ch3];
	if(vexRT[Btn8U] == 1) {
		motor[liftControl] = 127;
	}
	if(vexRT[Btn8D] == 1) {
		motor[liftControl] = -127;
	}
	if(vexRT[Btn8D] == 0 && vexRT[Btn8U] == 1) {
		motor[liftControl] = 0;
	}
}
}
